-- Copyright (C) 2026 Eccelerators GmbH
--
-- This code was generated by:
--
-- Livt Compiler v0.0.0-0000000
-- VHDL Extension for Livt v0.0.0-0000000
--
-- Further information at https://eccelerators.com/livt
--
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

use work.livt_lang_icomponent_package.all;
use work.livt_lang_icontext_package.all;
use work.livt_lang_package.all;
use work.livt_math_arithmetic_widearithmetic_g_24_4_sig_90219608922d_package.all;
use work.livt_math_arithmetic_widearithmeticprimitive_package.all;

entity livt_math_arithmetic_widearithmetic_g_24_4_sig_90219608922d is
	generic (
		LVT_RESET_ASYNC : boolean := false
	);
	port (
		ctor_lvt_context_in : in t_icontext_in;
		multiply_in : in t_widearithmetic_g_24_4_sig_90219608922d_multiply_in;
		multiply_out : out t_widearithmetic_g_24_4_sig_90219608922d_multiply_out;
		add_in : in t_widearithmetic_g_24_4_sig_90219608922d_add_in;
		add_out : out t_widearithmetic_g_24_4_sig_90219608922d_add_out;
		divideeven_in : in t_widearithmetic_g_24_4_sig_90219608922d_divideeven_in;
		divideeven_out : out t_widearithmetic_g_24_4_sig_90219608922d_divideeven_out;
		sqrt_in : in t_widearithmetic_g_24_4_sig_90219608922d_sqrt_in;
		sqrt_out : out t_widearithmetic_g_24_4_sig_90219608922d_sqrt_out;
		clamp_in : in t_widearithmetic_g_24_4_sig_90219608922d_clamp_in;
		clamp_out : out t_widearithmetic_g_24_4_sig_90219608922d_clamp_out;
		dividefloor_in : in t_widearithmetic_g_24_4_sig_90219608922d_dividefloor_in;
		dividefloor_out : out t_widearithmetic_g_24_4_sig_90219608922d_dividefloor_out;
		failed_in : in t_widearithmetic_g_24_4_sig_90219608922d_failed_in;
		failed_out : out t_widearithmetic_g_24_4_sig_90219608922d_failed_out
	);
end;

architecture behavioural of livt_math_arithmetic_widearithmetic_g_24_4_sig_90219608922d is

	constant OUTPUT_BITS : signed(31 downto 0) := signed'(x"00000018");
	constant OPERATIONS : signed(31 downto 0) := signed'(x"00000004");
	
	-- Functions
	type t_execute_state is (
		execute_lvt_idle,
		execute_lvt_startup,
		execute_lvt_0,
		execute_lvt_1,
		execute_lvt_10,
		execute_lvt_11,
		execute_lvt_2,
		execute_lvt_3,
		execute_lvt_4,
		execute_lvt_5,
		execute_lvt_6,
		execute_lvt_7,
		execute_lvt_8,
		execute_lvt_9,
		execute_dispatcher_pending_0,
		execute_dispatcher_pending_1,
		execute_lvt_return
	);
	
	type t_multiply_state is (
		multiply_lvt_idle,
		multiply_lvt_startup,
		multiply_lvt_0,
		multiply_lvt_1,
		multiply_lvt_2,
		multiply_lvt_3,
		multiply_lvt_4,
		multiply_lvt_5,
		multiply_dispatcher_pending_0,
		multiply_dispatcher_pending_1,
		multiply_lvt_return
	);
	
	type t_add_state is (
		add_lvt_idle,
		add_lvt_startup,
		add_lvt_0,
		add_lvt_1,
		add_lvt_2,
		add_lvt_3,
		add_lvt_4,
		add_lvt_5,
		add_dispatcher_pending_0,
		add_dispatcher_pending_1,
		add_lvt_return
	);
	
	type t_divideeven_state is (
		divideeven_lvt_idle,
		divideeven_lvt_startup,
		divideeven_lvt_0,
		divideeven_lvt_1,
		divideeven_lvt_2,
		divideeven_lvt_3,
		divideeven_lvt_4,
		divideeven_lvt_5,
		divideeven_dispatcher_pending_0,
		divideeven_dispatcher_pending_1,
		divideeven_lvt_return
	);
	
	type t_sqrt_state is (
		sqrt_lvt_idle,
		sqrt_lvt_startup,
		sqrt_lvt_0,
		sqrt_lvt_1,
		sqrt_lvt_2,
		sqrt_lvt_3,
		sqrt_lvt_4,
		sqrt_lvt_5,
		sqrt_dispatcher_pending_0,
		sqrt_dispatcher_pending_1,
		sqrt_lvt_return
	);
	
	type t_clamp_state is (
		clamp_lvt_idle,
		clamp_lvt_startup,
		clamp_lvt_0,
		clamp_lvt_1,
		clamp_lvt_2,
		clamp_lvt_3,
		clamp_lvt_4,
		clamp_lvt_5,
		clamp_dispatcher_pending_0,
		clamp_dispatcher_pending_1,
		clamp_lvt_return
	);
	
	type t_dividefloor_state is (
		dividefloor_lvt_idle,
		dividefloor_lvt_startup,
		dividefloor_lvt_0,
		dividefloor_lvt_1,
		dividefloor_lvt_2,
		dividefloor_lvt_3,
		dividefloor_lvt_4,
		dividefloor_lvt_5,
		dividefloor_dispatcher_pending_0,
		dividefloor_dispatcher_pending_1,
		dividefloor_lvt_return
	);
	
	type t_failed_state is (
		failed_lvt_idle,
		failed_lvt_startup,
		failed_lvt_0,
		failed_dispatcher_pending_0,
		failed_dispatcher_pending_1,
		failed_lvt_return
	);
	
	-- Function call dispatcher signals of functions
	signal this_dispatch_fn_multiply_execute : std_logic;
	signal this_dispatch_fn_add_execute : std_logic;
	signal this_dispatch_fn_divideeven_execute : std_logic;
	signal this_dispatch_fn_sqrt_execute : std_logic;
	signal this_dispatch_fn_clamp_execute : std_logic;
	signal this_dispatch_fn_dividefloor_execute : std_logic;
	
	type t_this_execute_in_references_requests is array (0 to 5) of t_widearithmetic_g_24_4_sig_90219608922d_execute_in;
	type t_this_execute_in_references_responses is array (0 to 5) of t_widearithmetic_g_24_4_sig_90219608922d_execute_out;
	signal this_execute_in_references_responses : t_this_execute_in_references_responses;
	signal this_execute_in_references_owner : integer range -1 to 5;
	signal this_multiply_execute_in_reference_out : t_widearithmetic_g_24_4_sig_90219608922d_execute_out;
	signal this_add_execute_in_reference_out : t_widearithmetic_g_24_4_sig_90219608922d_execute_out;
	signal this_divideeven_execute_in_reference_out : t_widearithmetic_g_24_4_sig_90219608922d_execute_out;
	signal this_sqrt_execute_in_reference_out : t_widearithmetic_g_24_4_sig_90219608922d_execute_out;
	signal this_clamp_execute_in_reference_out : t_widearithmetic_g_24_4_sig_90219608922d_execute_out;
	signal this_dividefloor_execute_in_reference_out : t_widearithmetic_g_24_4_sig_90219608922d_execute_out;
	-- Private fields
	signal this_lvt_context_in : t_icontext_in;
	signal this_primitive_in : t_widearithmeticprimitive_in;
	signal this_primitive_out : t_widearithmeticprimitive_out;
	signal this_request : std_logic;
	
	-- Function types
	signal this_execute_lvt_state : t_execute_state;
	signal this_execute_in : t_widearithmetic_g_24_4_sig_90219608922d_execute_in;
	signal this_execute_out : t_widearithmetic_g_24_4_sig_90219608922d_execute_out;
	
	signal this_multiply_lvt_state : t_multiply_state;
	signal this_multiply_in : t_widearithmetic_g_24_4_sig_90219608922d_multiply_in;
	signal this_multiply_out : t_widearithmetic_g_24_4_sig_90219608922d_multiply_out;
	
	signal this_add_lvt_state : t_add_state;
	signal this_add_in : t_widearithmetic_g_24_4_sig_90219608922d_add_in;
	signal this_add_out : t_widearithmetic_g_24_4_sig_90219608922d_add_out;
	
	signal this_divideeven_lvt_state : t_divideeven_state;
	signal this_divideeven_in : t_widearithmetic_g_24_4_sig_90219608922d_divideeven_in;
	signal this_divideeven_out : t_widearithmetic_g_24_4_sig_90219608922d_divideeven_out;
	
	signal this_sqrt_lvt_state : t_sqrt_state;
	signal this_sqrt_in : t_widearithmetic_g_24_4_sig_90219608922d_sqrt_in;
	signal this_sqrt_out : t_widearithmetic_g_24_4_sig_90219608922d_sqrt_out;
	
	signal this_clamp_lvt_state : t_clamp_state;
	signal this_clamp_in : t_widearithmetic_g_24_4_sig_90219608922d_clamp_in;
	signal this_clamp_out : t_widearithmetic_g_24_4_sig_90219608922d_clamp_out;
	
	signal this_dividefloor_lvt_state : t_dividefloor_state;
	signal this_dividefloor_in : t_widearithmetic_g_24_4_sig_90219608922d_dividefloor_in;
	signal this_dividefloor_out : t_widearithmetic_g_24_4_sig_90219608922d_dividefloor_out;
	
	signal this_failed_lvt_state : t_failed_state;
	signal this_failed_in : t_widearithmetic_g_24_4_sig_90219608922d_failed_in;
	signal this_failed_out : t_widearithmetic_g_24_4_sig_90219608922d_failed_out;
	
	-- Dispatcher function types
	signal this_multiply_execute_in : t_widearithmetic_g_24_4_sig_90219608922d_execute_in;
	signal this_add_execute_in : t_widearithmetic_g_24_4_sig_90219608922d_execute_in;
	signal this_divideeven_execute_in : t_widearithmetic_g_24_4_sig_90219608922d_execute_in;
	signal this_sqrt_execute_in : t_widearithmetic_g_24_4_sig_90219608922d_execute_in;
	signal this_clamp_execute_in : t_widearithmetic_g_24_4_sig_90219608922d_execute_in;
	signal this_dividefloor_execute_in : t_widearithmetic_g_24_4_sig_90219608922d_execute_in;
	
	-- Field accessor signals
	signal this_lvt_new_primitive_initialized : std_logic;
	signal this_execute_request_set : std_logic;
	signal this_execute_primitive_operation_set : std_logic;
	signal this_execute_primitive_a_set : std_logic;
	signal this_execute_primitive_b_set : std_logic;
	signal this_execute_primitive_outputbits_set : std_logic;
	signal this_execute_primitive_request_set : std_logic;
	signal this_execute_request : std_logic;
	signal this_execute_primitive_operation : signed(31 downto 0);
	signal this_execute_primitive_a : std_logic_vector(63 downto 0);
	signal this_execute_primitive_b : std_logic_vector(63 downto 0);
	signal this_execute_primitive_outputbits : signed(31 downto 0);
	signal this_execute_primitive_request : std_logic;
	signal this_primitive_acknowledge : std_logic;
	signal this_primitive_result : std_logic_vector(63 downto 0);
	signal this_primitive_failed : boolean;
	
begin

	-- Public field assignments
	this_lvt_context_in.clk <= ctor_lvt_context_in.clk;
	this_lvt_context_in.rst <= ctor_lvt_context_in.rst;
	this_lvt_context_in.tickspersecond <= ctor_lvt_context_in.tickspersecond;
	this_lvt_context_in.periodns <= ctor_lvt_context_in.periodns;
	this_lvt_context_in.hightimens <= ctor_lvt_context_in.hightimens;
	this_lvt_context_in.lowtimens <= ctor_lvt_context_in.lowtimens;
	
	-- Field accessors
	primitive_accessor_reset_sync : if not LVT_RESET_ASYNC generate
		primitive_accessor : process(this_lvt_context_in.clk) is
		begin
			if rising_edge(this_lvt_context_in.clk) then
				if this_lvt_context_in.rst = '1' then
					this_lvt_new_primitive_initialized <= '0';
					this_primitive_in <= (request => '0',
					operation => (others => '0'),
					a => (others => '0'),
					b => (others => '0'),
					outputbits => (others => '0'),
					operations => (others => '0'));
				else
					if this_lvt_new_primitive_initialized = '0' then
						this_primitive_in.operations <= OPERATIONS;
						this_lvt_new_primitive_initialized <= '1';
					end if;
					if this_lvt_new_primitive_initialized = '1' then
						if this_execute_primitive_operation_set = '1' or
							this_execute_primitive_a_set = '1' or
							this_execute_primitive_b_set = '1' or
							this_execute_primitive_outputbits_set = '1' then
							this_primitive_in.operation <= this_execute_primitive_operation;
							this_primitive_in.a <= this_execute_primitive_a;
							this_primitive_in.b <= this_execute_primitive_b;
							this_primitive_in.outputbits <= this_execute_primitive_outputbits;
						end if;
						if this_execute_primitive_request_set = '1' then
							this_primitive_in.request <= this_execute_primitive_request;
						end if;
					end if;
				end if;
			end if;
		end process;
	end generate;
	primitive_accessor_reset_async : if LVT_RESET_ASYNC generate
		primitive_accessor : process(this_lvt_context_in.clk, this_lvt_context_in.rst) is
		begin
			if this_lvt_context_in.rst = '1' then
				this_lvt_new_primitive_initialized <= '0';
				this_primitive_in <= (request => '0',
				operation => (others => '0'),
				a => (others => '0'),
				b => (others => '0'),
				outputbits => (others => '0'),
				operations => (others => '0'));
			elsif rising_edge(this_lvt_context_in.clk) then
				if this_lvt_new_primitive_initialized = '0' then
					this_primitive_in.operations <= OPERATIONS;
					this_lvt_new_primitive_initialized <= '1';
				end if;
				if this_lvt_new_primitive_initialized = '1' then
					if this_execute_primitive_operation_set = '1' or
						this_execute_primitive_a_set = '1' or
						this_execute_primitive_b_set = '1' or
						this_execute_primitive_outputbits_set = '1' then
						this_primitive_in.operation <= this_execute_primitive_operation;
						this_primitive_in.a <= this_execute_primitive_a;
						this_primitive_in.b <= this_execute_primitive_b;
						this_primitive_in.outputbits <= this_execute_primitive_outputbits;
					end if;
					if this_execute_primitive_request_set = '1' then
						this_primitive_in.request <= this_execute_primitive_request;
					end if;
				end if;
			end if;
		end process;
	end generate;
	
	request_accessor_reset_sync : if not LVT_RESET_ASYNC generate
		request_accessor : process(this_lvt_context_in.clk) is
		begin
			if rising_edge(this_lvt_context_in.clk) then
				if this_lvt_context_in.rst = '1' then
					this_request <= '0';
				else
					if this_execute_request_set = '1' then
						this_request <= this_execute_request;
					end if;
				end if;
			end if;
		end process;
	end generate;
	request_accessor_reset_async : if LVT_RESET_ASYNC generate
		request_accessor : process(this_lvt_context_in.clk, this_lvt_context_in.rst) is
		begin
			if this_lvt_context_in.rst = '1' then
				this_request <= '0';
			elsif rising_edge(this_lvt_context_in.clk) then
				if this_execute_request_set = '1' then
					this_request <= this_execute_request;
				end if;
			end if;
		end process;
	end generate;
	
	-- Opaque component output assignments
	this_primitive_out.acknowledge <= this_primitive_acknowledge;
	this_primitive_out.result <= this_primitive_result;
	this_primitive_out.failed <= this_primitive_failed;
	
	-- Entity port connections of public functions
	multiply_out <= this_multiply_out;
	this_multiply_in <= multiply_in;
	add_out <= this_add_out;
	this_add_in <= add_in;
	divideeven_out <= this_divideeven_out;
	this_divideeven_in <= divideeven_in;
	sqrt_out <= this_sqrt_out;
	this_sqrt_in <= sqrt_in;
	clamp_out <= this_clamp_out;
	this_clamp_in <= clamp_in;
	dividefloor_out <= this_dividefloor_out;
	this_dividefloor_in <= dividefloor_in;
	failed_out <= this_failed_out;
	this_failed_in <= failed_in;
	
	this_multiply_execute_in_reference_out <= this_execute_in_references_responses(0);
	this_add_execute_in_reference_out <= this_execute_in_references_responses(1);
	this_divideeven_execute_in_reference_out <= this_execute_in_references_responses(2);
	this_sqrt_execute_in_reference_out <= this_execute_in_references_responses(3);
	this_clamp_execute_in_reference_out <= this_execute_in_references_responses(4);
	this_dividefloor_execute_in_reference_out <= this_execute_in_references_responses(5);
	this_execute_in_references_arbiter_reset_sync : if not LVT_RESET_ASYNC generate
		this_execute_in_references_arbiter : process(this_lvt_context_in.clk) is
			variable pending : std_logic_vector(5 downto 0);
			variable previous_run : std_logic_vector(5 downto 0);
			variable queued : t_this_execute_in_references_requests;
			variable owner : integer range -1 to 5;
			variable last_owner : integer range 0 to 5;
			variable candidate : integer range 0 to 5;
			variable seen_busy : boolean;
		begin
			if rising_edge(this_lvt_context_in.clk) then
				if this_lvt_context_in.rst = '1' then
					pending := (others => '0');
					previous_run := (others => '0');
					queued := (others => (run => '0',
					op => (others => '0'),
					a => (others => '0'),
					b => (others => '0')));
					owner := -1;
					last_owner := 5;
					seen_busy := false;
					this_execute_in_references_owner <= -1;
					this_execute_in_references_responses <= (others => (busy => '0'));
					this_execute_in <= (run => '0',
					op => (others => '0'),
					a => (others => '0'),
					b => (others => '0'));
				else
					this_execute_in.run <= '0';
					if (this_dispatch_fn_multiply_execute = '1') and this_multiply_execute_in.run = '1' then
					    if previous_run(0) = '0' then
					        pending(0) := '1';
					        queued(0) := this_multiply_execute_in;
					        this_execute_in_references_responses(0).busy <= '1';
					    end if;
					    previous_run(0) := '1';
					else
					    previous_run(0) := '0';
					end if;
					if (this_dispatch_fn_add_execute = '1') and this_add_execute_in.run = '1' then
					    if previous_run(1) = '0' then
					        pending(1) := '1';
					        queued(1) := this_add_execute_in;
					        this_execute_in_references_responses(1).busy <= '1';
					    end if;
					    previous_run(1) := '1';
					else
					    previous_run(1) := '0';
					end if;
					if (this_dispatch_fn_divideeven_execute = '1') and this_divideeven_execute_in.run = '1' then
					    if previous_run(2) = '0' then
					        pending(2) := '1';
					        queued(2) := this_divideeven_execute_in;
					        this_execute_in_references_responses(2).busy <= '1';
					    end if;
					    previous_run(2) := '1';
					else
					    previous_run(2) := '0';
					end if;
					if (this_dispatch_fn_sqrt_execute = '1') and this_sqrt_execute_in.run = '1' then
					    if previous_run(3) = '0' then
					        pending(3) := '1';
					        queued(3) := this_sqrt_execute_in;
					        this_execute_in_references_responses(3).busy <= '1';
					    end if;
					    previous_run(3) := '1';
					else
					    previous_run(3) := '0';
					end if;
					if (this_dispatch_fn_clamp_execute = '1') and this_clamp_execute_in.run = '1' then
					    if previous_run(4) = '0' then
					        pending(4) := '1';
					        queued(4) := this_clamp_execute_in;
					        this_execute_in_references_responses(4).busy <= '1';
					    end if;
					    previous_run(4) := '1';
					else
					    previous_run(4) := '0';
					end if;
					if (this_dispatch_fn_dividefloor_execute = '1') and this_dividefloor_execute_in.run = '1' then
					    if previous_run(5) = '0' then
					        pending(5) := '1';
					        queued(5) := this_dividefloor_execute_in;
					        this_execute_in_references_responses(5).busy <= '1';
					    end if;
					    previous_run(5) := '1';
					else
					    previous_run(5) := '0';
					end if;
					if owner >= 0 then
					    if this_execute_out.busy = '1' then seen_busy := true; end if;
					    if seen_busy and this_execute_out.busy = '0' then
					        this_execute_in_references_responses(owner) <= this_execute_out;
					        last_owner := owner;
					        owner := -1;
					    end if;
					else
					    for offset in 1 to 6 loop
					        candidate := (last_owner + offset) mod 6;
					        if pending(candidate) = '1' then
					            owner := candidate;
					            pending(candidate) := '0';
					            seen_busy := false;
					            this_execute_in <= queued(candidate);
					            this_execute_in.run <= '1';
					            exit;
					        end if;
					    end loop;
					end if;
					this_execute_in_references_owner <= owner;
				end if;
			end if;
		end process;
	end generate;
	this_execute_in_references_arbiter_reset_async : if LVT_RESET_ASYNC generate
		this_execute_in_references_arbiter : process(this_lvt_context_in.clk, this_lvt_context_in.rst) is
			variable pending : std_logic_vector(5 downto 0);
			variable previous_run : std_logic_vector(5 downto 0);
			variable queued : t_this_execute_in_references_requests;
			variable owner : integer range -1 to 5;
			variable last_owner : integer range 0 to 5;
			variable candidate : integer range 0 to 5;
			variable seen_busy : boolean;
		begin
			if this_lvt_context_in.rst = '1' then
				pending := (others => '0');
				previous_run := (others => '0');
				queued := (others => (run => '0',
				op => (others => '0'),
				a => (others => '0'),
				b => (others => '0')));
				owner := -1;
				last_owner := 5;
				seen_busy := false;
				this_execute_in_references_owner <= -1;
				this_execute_in_references_responses <= (others => (busy => '0'));
				this_execute_in <= (run => '0',
				op => (others => '0'),
				a => (others => '0'),
				b => (others => '0'));
			elsif rising_edge(this_lvt_context_in.clk) then
				this_execute_in.run <= '0';
				if (this_dispatch_fn_multiply_execute = '1') and this_multiply_execute_in.run = '1' then
				    if previous_run(0) = '0' then
				        pending(0) := '1';
				        queued(0) := this_multiply_execute_in;
				        this_execute_in_references_responses(0).busy <= '1';
				    end if;
				    previous_run(0) := '1';
				else
				    previous_run(0) := '0';
				end if;
				if (this_dispatch_fn_add_execute = '1') and this_add_execute_in.run = '1' then
				    if previous_run(1) = '0' then
				        pending(1) := '1';
				        queued(1) := this_add_execute_in;
				        this_execute_in_references_responses(1).busy <= '1';
				    end if;
				    previous_run(1) := '1';
				else
				    previous_run(1) := '0';
				end if;
				if (this_dispatch_fn_divideeven_execute = '1') and this_divideeven_execute_in.run = '1' then
				    if previous_run(2) = '0' then
				        pending(2) := '1';
				        queued(2) := this_divideeven_execute_in;
				        this_execute_in_references_responses(2).busy <= '1';
				    end if;
				    previous_run(2) := '1';
				else
				    previous_run(2) := '0';
				end if;
				if (this_dispatch_fn_sqrt_execute = '1') and this_sqrt_execute_in.run = '1' then
				    if previous_run(3) = '0' then
				        pending(3) := '1';
				        queued(3) := this_sqrt_execute_in;
				        this_execute_in_references_responses(3).busy <= '1';
				    end if;
				    previous_run(3) := '1';
				else
				    previous_run(3) := '0';
				end if;
				if (this_dispatch_fn_clamp_execute = '1') and this_clamp_execute_in.run = '1' then
				    if previous_run(4) = '0' then
				        pending(4) := '1';
				        queued(4) := this_clamp_execute_in;
				        this_execute_in_references_responses(4).busy <= '1';
				    end if;
				    previous_run(4) := '1';
				else
				    previous_run(4) := '0';
				end if;
				if (this_dispatch_fn_dividefloor_execute = '1') and this_dividefloor_execute_in.run = '1' then
				    if previous_run(5) = '0' then
				        pending(5) := '1';
				        queued(5) := this_dividefloor_execute_in;
				        this_execute_in_references_responses(5).busy <= '1';
				    end if;
				    previous_run(5) := '1';
				else
				    previous_run(5) := '0';
				end if;
				if owner >= 0 then
				    if this_execute_out.busy = '1' then seen_busy := true; end if;
				    if seen_busy and this_execute_out.busy = '0' then
				        this_execute_in_references_responses(owner) <= this_execute_out;
				        last_owner := owner;
				        owner := -1;
				    end if;
				else
				    for offset in 1 to 6 loop
				        candidate := (last_owner + offset) mod 6;
				        if pending(candidate) = '1' then
				            owner := candidate;
				            pending(candidate) := '0';
				            seen_busy := false;
				            this_execute_in <= queued(candidate);
				            this_execute_in.run <= '1';
				            exit;
				        end if;
				    end loop;
				end if;
				this_execute_in_references_owner <= owner;
			end if;
		end process;
	end generate;
	execute_fn_reset_sync : if not LVT_RESET_ASYNC generate
		execute_fn : process(this_lvt_context_in.clk) is
			variable execute_request_wait_cycles : integer := REF_WAIT_CYCLES;
			variable execute_primitive_operation_wait_cycles : integer := REF_WAIT_CYCLES;
			variable execute_primitive_a_wait_cycles : integer := REF_WAIT_CYCLES;
			variable execute_primitive_b_wait_cycles : integer := REF_WAIT_CYCLES;
			variable execute_primitive_outputbits_wait_cycles : integer := REF_WAIT_CYCLES;
			variable execute_primitive_request_wait_cycles : integer := REF_WAIT_CYCLES;
			variable var_fwd_request : std_logic := '0';
			variable execute_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_execute_in;
		begin
			if rising_edge(this_lvt_context_in.clk) then
				if this_lvt_context_in.rst = '1' then
					execute_request_wait_cycles := REF_WAIT_CYCLES;
					execute_primitive_operation_wait_cycles := REF_WAIT_CYCLES;
					execute_primitive_a_wait_cycles := REF_WAIT_CYCLES;
					execute_primitive_b_wait_cycles := REF_WAIT_CYCLES;
					execute_primitive_outputbits_wait_cycles := REF_WAIT_CYCLES;
					execute_primitive_request_wait_cycles := REF_WAIT_CYCLES;
					var_fwd_request := '0';
					this_execute_request <= '0';
					this_execute_primitive_operation <= (others => '0');
					this_execute_primitive_a <= (others => '0');
					this_execute_primitive_b <= (others => '0');
					this_execute_primitive_outputbits <= (others => '0');
					this_execute_primitive_request <= '0';
					this_execute_request_set <= '0';
					this_execute_primitive_operation_set <= '0';
					this_execute_primitive_a_set <= '0';
					this_execute_primitive_b_set <= '0';
					this_execute_primitive_outputbits_set <= '0';
					this_execute_primitive_request_set <= '0';
					this_execute_out <= (busy => '0');
					this_execute_lvt_state <= execute_lvt_idle;
				else
					if this_execute_request_set = '1' then
						if execute_request_wait_cycles /= 0 then
							execute_request_wait_cycles := execute_request_wait_cycles - 1;
						else
							execute_request_wait_cycles := REF_WAIT_CYCLES;
							this_execute_request_set <= '0';
						end if;
					end if;
					if this_execute_primitive_operation_set = '1' then
						if execute_primitive_operation_wait_cycles /= 0 then
							execute_primitive_operation_wait_cycles := execute_primitive_operation_wait_cycles - 1;
						else
							execute_primitive_operation_wait_cycles := REF_WAIT_CYCLES;
							this_execute_primitive_operation_set <= '0';
						end if;
					end if;
					if this_execute_primitive_a_set = '1' then
						if execute_primitive_a_wait_cycles /= 0 then
							execute_primitive_a_wait_cycles := execute_primitive_a_wait_cycles - 1;
						else
							execute_primitive_a_wait_cycles := REF_WAIT_CYCLES;
							this_execute_primitive_a_set <= '0';
						end if;
					end if;
					if this_execute_primitive_b_set = '1' then
						if execute_primitive_b_wait_cycles /= 0 then
							execute_primitive_b_wait_cycles := execute_primitive_b_wait_cycles - 1;
						else
							execute_primitive_b_wait_cycles := REF_WAIT_CYCLES;
							this_execute_primitive_b_set <= '0';
						end if;
					end if;
					if this_execute_primitive_outputbits_set = '1' then
						if execute_primitive_outputbits_wait_cycles /= 0 then
							execute_primitive_outputbits_wait_cycles := execute_primitive_outputbits_wait_cycles - 1;
						else
							execute_primitive_outputbits_wait_cycles := REF_WAIT_CYCLES;
							this_execute_primitive_outputbits_set <= '0';
						end if;
					end if;
					if this_execute_primitive_request_set = '1' then
						if execute_primitive_request_wait_cycles /= 0 then
							execute_primitive_request_wait_cycles := execute_primitive_request_wait_cycles - 1;
						else
							execute_primitive_request_wait_cycles := REF_WAIT_CYCLES;
							this_execute_primitive_request_set <= '0';
						end if;
					end if;
					case this_execute_lvt_state is
						when execute_lvt_idle =>
							if this_execute_in.run = '1' then
								execute_lvt_startup_arguments.op := this_execute_in.op;
								execute_lvt_startup_arguments.a := this_execute_in.a;
								execute_lvt_startup_arguments.b := this_execute_in.b;
								execute_request_wait_cycles := REF_WAIT_CYCLES;
								execute_primitive_operation_wait_cycles := REF_WAIT_CYCLES;
								execute_primitive_a_wait_cycles := REF_WAIT_CYCLES;
								execute_primitive_b_wait_cycles := REF_WAIT_CYCLES;
								execute_primitive_outputbits_wait_cycles := REF_WAIT_CYCLES;
								execute_primitive_request_wait_cycles := REF_WAIT_CYCLES;
								var_fwd_request := this_request;
								this_execute_out.busy <= '1';
								if this_lvt_new_primitive_initialized = '1' then
									this_execute_lvt_state <= execute_lvt_0;
								else
									this_execute_lvt_state <= execute_lvt_startup;
								end if;
							end if;
						when execute_lvt_startup =>
							if this_lvt_new_primitive_initialized = '1' then
								this_execute_lvt_state <= execute_lvt_0;
							end if;
						when execute_lvt_0 =>
							this_execute_primitive_operation_set <= '1';
							this_execute_primitive_operation <= execute_lvt_startup_arguments.op;
							this_execute_primitive_a_set <= '1';
							this_execute_primitive_a <= execute_lvt_startup_arguments.a;
							this_execute_primitive_b_set <= '1';
							this_execute_primitive_b <= execute_lvt_startup_arguments.b;
							this_execute_primitive_outputbits_set <= '1';
							this_execute_primitive_outputbits <= OUTPUT_BITS;
							this_execute_lvt_state <= execute_lvt_1;
						when execute_lvt_1 =>
							this_execute_request_set <= '1';
							this_execute_request <= not var_fwd_request;
							var_fwd_request := not var_fwd_request;
							this_execute_lvt_state <= execute_lvt_2;
						when execute_lvt_2 =>
							this_execute_lvt_state <= execute_lvt_3;
						when execute_lvt_3 =>
							this_execute_lvt_state <= execute_lvt_4;
						when execute_lvt_4 =>
							this_execute_lvt_state <= execute_lvt_5;
						when execute_lvt_5 =>
							this_execute_primitive_request_set <= '1';
							this_execute_primitive_request <= var_fwd_request;
							this_execute_lvt_state <= execute_lvt_6;
						when execute_lvt_6 =>
							this_execute_lvt_state <= execute_lvt_7;
						when execute_lvt_7 =>
							this_execute_lvt_state <= execute_lvt_8;
						when execute_lvt_8 =>
							this_execute_lvt_state <= execute_lvt_9;
						when execute_lvt_9 =>
							if this_primitive_out.acknowledge /= var_fwd_request then
								this_execute_lvt_state <= execute_lvt_10;
							else
								this_execute_lvt_state <= execute_lvt_return;
							end if;
						when execute_lvt_10 =>
							this_execute_lvt_state <= execute_lvt_11;
						when execute_lvt_11 =>
							this_execute_lvt_state <= execute_lvt_9;
						when execute_lvt_return =>
							this_execute_lvt_state <= execute_dispatcher_pending_0;
						when execute_dispatcher_pending_0 =>
							this_execute_lvt_state <= execute_dispatcher_pending_1;
						when execute_dispatcher_pending_1 =>
							this_execute_out.busy <= '0';
							this_execute_lvt_state <= execute_lvt_idle;
					end case;
				end if;
			end if;
		end process;
	end generate;
	execute_fn_reset_async : if LVT_RESET_ASYNC generate
		execute_fn : process(this_lvt_context_in.clk, this_lvt_context_in.rst) is
			variable execute_request_wait_cycles : integer := REF_WAIT_CYCLES;
			variable execute_primitive_operation_wait_cycles : integer := REF_WAIT_CYCLES;
			variable execute_primitive_a_wait_cycles : integer := REF_WAIT_CYCLES;
			variable execute_primitive_b_wait_cycles : integer := REF_WAIT_CYCLES;
			variable execute_primitive_outputbits_wait_cycles : integer := REF_WAIT_CYCLES;
			variable execute_primitive_request_wait_cycles : integer := REF_WAIT_CYCLES;
			variable var_fwd_request : std_logic := '0';
			variable execute_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_execute_in;
		begin
			if this_lvt_context_in.rst = '1' then
				execute_request_wait_cycles := REF_WAIT_CYCLES;
				execute_primitive_operation_wait_cycles := REF_WAIT_CYCLES;
				execute_primitive_a_wait_cycles := REF_WAIT_CYCLES;
				execute_primitive_b_wait_cycles := REF_WAIT_CYCLES;
				execute_primitive_outputbits_wait_cycles := REF_WAIT_CYCLES;
				execute_primitive_request_wait_cycles := REF_WAIT_CYCLES;
				var_fwd_request := '0';
				this_execute_request <= '0';
				this_execute_primitive_operation <= (others => '0');
				this_execute_primitive_a <= (others => '0');
				this_execute_primitive_b <= (others => '0');
				this_execute_primitive_outputbits <= (others => '0');
				this_execute_primitive_request <= '0';
				this_execute_request_set <= '0';
				this_execute_primitive_operation_set <= '0';
				this_execute_primitive_a_set <= '0';
				this_execute_primitive_b_set <= '0';
				this_execute_primitive_outputbits_set <= '0';
				this_execute_primitive_request_set <= '0';
				this_execute_out <= (busy => '0');
				this_execute_lvt_state <= execute_lvt_idle;
			elsif rising_edge(this_lvt_context_in.clk) then
				if this_execute_request_set = '1' then
					if execute_request_wait_cycles /= 0 then
						execute_request_wait_cycles := execute_request_wait_cycles - 1;
					else
						execute_request_wait_cycles := REF_WAIT_CYCLES;
						this_execute_request_set <= '0';
					end if;
				end if;
				if this_execute_primitive_operation_set = '1' then
					if execute_primitive_operation_wait_cycles /= 0 then
						execute_primitive_operation_wait_cycles := execute_primitive_operation_wait_cycles - 1;
					else
						execute_primitive_operation_wait_cycles := REF_WAIT_CYCLES;
						this_execute_primitive_operation_set <= '0';
					end if;
				end if;
				if this_execute_primitive_a_set = '1' then
					if execute_primitive_a_wait_cycles /= 0 then
						execute_primitive_a_wait_cycles := execute_primitive_a_wait_cycles - 1;
					else
						execute_primitive_a_wait_cycles := REF_WAIT_CYCLES;
						this_execute_primitive_a_set <= '0';
					end if;
				end if;
				if this_execute_primitive_b_set = '1' then
					if execute_primitive_b_wait_cycles /= 0 then
						execute_primitive_b_wait_cycles := execute_primitive_b_wait_cycles - 1;
					else
						execute_primitive_b_wait_cycles := REF_WAIT_CYCLES;
						this_execute_primitive_b_set <= '0';
					end if;
				end if;
				if this_execute_primitive_outputbits_set = '1' then
					if execute_primitive_outputbits_wait_cycles /= 0 then
						execute_primitive_outputbits_wait_cycles := execute_primitive_outputbits_wait_cycles - 1;
					else
						execute_primitive_outputbits_wait_cycles := REF_WAIT_CYCLES;
						this_execute_primitive_outputbits_set <= '0';
					end if;
				end if;
				if this_execute_primitive_request_set = '1' then
					if execute_primitive_request_wait_cycles /= 0 then
						execute_primitive_request_wait_cycles := execute_primitive_request_wait_cycles - 1;
					else
						execute_primitive_request_wait_cycles := REF_WAIT_CYCLES;
						this_execute_primitive_request_set <= '0';
					end if;
				end if;
				case this_execute_lvt_state is
					when execute_lvt_idle =>
						if this_execute_in.run = '1' then
							execute_lvt_startup_arguments.op := this_execute_in.op;
							execute_lvt_startup_arguments.a := this_execute_in.a;
							execute_lvt_startup_arguments.b := this_execute_in.b;
							execute_request_wait_cycles := REF_WAIT_CYCLES;
							execute_primitive_operation_wait_cycles := REF_WAIT_CYCLES;
							execute_primitive_a_wait_cycles := REF_WAIT_CYCLES;
							execute_primitive_b_wait_cycles := REF_WAIT_CYCLES;
							execute_primitive_outputbits_wait_cycles := REF_WAIT_CYCLES;
							execute_primitive_request_wait_cycles := REF_WAIT_CYCLES;
							var_fwd_request := this_request;
							this_execute_out.busy <= '1';
							if this_lvt_new_primitive_initialized = '1' then
								this_execute_lvt_state <= execute_lvt_0;
							else
								this_execute_lvt_state <= execute_lvt_startup;
							end if;
						end if;
					when execute_lvt_startup =>
						if this_lvt_new_primitive_initialized = '1' then
							this_execute_lvt_state <= execute_lvt_0;
						end if;
					when execute_lvt_0 =>
						this_execute_primitive_operation_set <= '1';
						this_execute_primitive_operation <= execute_lvt_startup_arguments.op;
						this_execute_primitive_a_set <= '1';
						this_execute_primitive_a <= execute_lvt_startup_arguments.a;
						this_execute_primitive_b_set <= '1';
						this_execute_primitive_b <= execute_lvt_startup_arguments.b;
						this_execute_primitive_outputbits_set <= '1';
						this_execute_primitive_outputbits <= OUTPUT_BITS;
						this_execute_lvt_state <= execute_lvt_1;
					when execute_lvt_1 =>
						this_execute_request_set <= '1';
						this_execute_request <= not var_fwd_request;
						var_fwd_request := not var_fwd_request;
						this_execute_lvt_state <= execute_lvt_2;
					when execute_lvt_2 =>
						this_execute_lvt_state <= execute_lvt_3;
					when execute_lvt_3 =>
						this_execute_lvt_state <= execute_lvt_4;
					when execute_lvt_4 =>
						this_execute_lvt_state <= execute_lvt_5;
					when execute_lvt_5 =>
						this_execute_primitive_request_set <= '1';
						this_execute_primitive_request <= var_fwd_request;
						this_execute_lvt_state <= execute_lvt_6;
					when execute_lvt_6 =>
						this_execute_lvt_state <= execute_lvt_7;
					when execute_lvt_7 =>
						this_execute_lvt_state <= execute_lvt_8;
					when execute_lvt_8 =>
						this_execute_lvt_state <= execute_lvt_9;
					when execute_lvt_9 =>
						if this_primitive_out.acknowledge /= var_fwd_request then
							this_execute_lvt_state <= execute_lvt_10;
						else
							this_execute_lvt_state <= execute_lvt_return;
						end if;
					when execute_lvt_10 =>
						this_execute_lvt_state <= execute_lvt_11;
					when execute_lvt_11 =>
						this_execute_lvt_state <= execute_lvt_9;
					when execute_lvt_return =>
						this_execute_lvt_state <= execute_dispatcher_pending_0;
					when execute_dispatcher_pending_0 =>
						this_execute_lvt_state <= execute_dispatcher_pending_1;
					when execute_dispatcher_pending_1 =>
						this_execute_out.busy <= '0';
						this_execute_lvt_state <= execute_lvt_idle;
				end case;
			end if;
		end process;
	end generate;
	multiply_fn_reset_sync : if not LVT_RESET_ASYNC generate
		multiply_fn : process(this_lvt_context_in.clk) is
			variable multiply_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_multiply_in;
		begin
			if rising_edge(this_lvt_context_in.clk) then
				if this_lvt_context_in.rst = '1' then
					this_dispatch_fn_multiply_execute <= '0';
					this_multiply_out <= (busy => '0',
					return_value => (others => '0'));
					this_multiply_execute_in <= (run => '0',
					op => (others => '0'),
					a => (others => '0'),
					b => (others => '0'));
					this_multiply_out.return_value <= (others => '0');
					this_multiply_lvt_state <= multiply_lvt_idle;
				else
					case this_multiply_lvt_state is
						when multiply_lvt_idle =>
							if this_multiply_in.run = '1' then
								multiply_lvt_startup_arguments.a := this_multiply_in.a;
								multiply_lvt_startup_arguments.b := this_multiply_in.b;
								this_multiply_out.busy <= '1';
								if this_lvt_new_primitive_initialized = '1' then
									this_multiply_lvt_state <= multiply_lvt_0;
								else
									this_multiply_lvt_state <= multiply_lvt_startup;
								end if;
							end if;
						when multiply_lvt_startup =>
							if this_lvt_new_primitive_initialized = '1' then
								this_multiply_lvt_state <= multiply_lvt_0;
							end if;
						when multiply_lvt_0 =>
							this_multiply_execute_in.run <= '1';
							this_dispatch_fn_multiply_execute <= '1';
							this_multiply_execute_in.a <= multiply_lvt_startup_arguments.a;
							this_multiply_execute_in.b <= multiply_lvt_startup_arguments.b;
							this_multiply_execute_in.op <= signed'(x"00000000");
							this_multiply_lvt_state <= multiply_lvt_1;
						when multiply_lvt_1 =>
							this_multiply_lvt_state <= multiply_lvt_2;
						when multiply_lvt_2 =>
							this_multiply_execute_in.run <= '0';
							this_multiply_lvt_state <= multiply_lvt_3;
						when multiply_lvt_3 =>
							this_multiply_lvt_state <= multiply_lvt_4;
						when multiply_lvt_4 =>
							if this_multiply_execute_in_reference_out.busy = '0' then
								this_dispatch_fn_multiply_execute <= '0';
								this_multiply_lvt_state <= multiply_lvt_5;
							end if;
						when multiply_lvt_5 =>
							this_multiply_out.return_value <= this_primitive_out.result;
							this_multiply_lvt_state <= multiply_lvt_return;
						when multiply_lvt_return =>
							this_multiply_lvt_state <= multiply_dispatcher_pending_0;
						when multiply_dispatcher_pending_0 =>
							this_multiply_lvt_state <= multiply_dispatcher_pending_1;
						when multiply_dispatcher_pending_1 =>
							this_multiply_out.busy <= '0';
							this_multiply_lvt_state <= multiply_lvt_idle;
					end case;
				end if;
			end if;
		end process;
	end generate;
	multiply_fn_reset_async : if LVT_RESET_ASYNC generate
		multiply_fn : process(this_lvt_context_in.clk, this_lvt_context_in.rst) is
			variable multiply_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_multiply_in;
		begin
			if this_lvt_context_in.rst = '1' then
				this_dispatch_fn_multiply_execute <= '0';
				this_multiply_out <= (busy => '0',
				return_value => (others => '0'));
				this_multiply_execute_in <= (run => '0',
				op => (others => '0'),
				a => (others => '0'),
				b => (others => '0'));
				this_multiply_out.return_value <= (others => '0');
				this_multiply_lvt_state <= multiply_lvt_idle;
			elsif rising_edge(this_lvt_context_in.clk) then
				case this_multiply_lvt_state is
					when multiply_lvt_idle =>
						if this_multiply_in.run = '1' then
							multiply_lvt_startup_arguments.a := this_multiply_in.a;
							multiply_lvt_startup_arguments.b := this_multiply_in.b;
							this_multiply_out.busy <= '1';
							if this_lvt_new_primitive_initialized = '1' then
								this_multiply_lvt_state <= multiply_lvt_0;
							else
								this_multiply_lvt_state <= multiply_lvt_startup;
							end if;
						end if;
					when multiply_lvt_startup =>
						if this_lvt_new_primitive_initialized = '1' then
							this_multiply_lvt_state <= multiply_lvt_0;
						end if;
					when multiply_lvt_0 =>
						this_multiply_execute_in.run <= '1';
						this_dispatch_fn_multiply_execute <= '1';
						this_multiply_execute_in.a <= multiply_lvt_startup_arguments.a;
						this_multiply_execute_in.b <= multiply_lvt_startup_arguments.b;
						this_multiply_execute_in.op <= signed'(x"00000000");
						this_multiply_lvt_state <= multiply_lvt_1;
					when multiply_lvt_1 =>
						this_multiply_lvt_state <= multiply_lvt_2;
					when multiply_lvt_2 =>
						this_multiply_execute_in.run <= '0';
						this_multiply_lvt_state <= multiply_lvt_3;
					when multiply_lvt_3 =>
						this_multiply_lvt_state <= multiply_lvt_4;
					when multiply_lvt_4 =>
						if this_multiply_execute_in_reference_out.busy = '0' then
							this_dispatch_fn_multiply_execute <= '0';
							this_multiply_lvt_state <= multiply_lvt_5;
						end if;
					when multiply_lvt_5 =>
						this_multiply_out.return_value <= this_primitive_out.result;
						this_multiply_lvt_state <= multiply_lvt_return;
					when multiply_lvt_return =>
						this_multiply_lvt_state <= multiply_dispatcher_pending_0;
					when multiply_dispatcher_pending_0 =>
						this_multiply_lvt_state <= multiply_dispatcher_pending_1;
					when multiply_dispatcher_pending_1 =>
						this_multiply_out.busy <= '0';
						this_multiply_lvt_state <= multiply_lvt_idle;
				end case;
			end if;
		end process;
	end generate;
	add_fn_reset_sync : if not LVT_RESET_ASYNC generate
		add_fn : process(this_lvt_context_in.clk) is
			variable add_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_add_in;
		begin
			if rising_edge(this_lvt_context_in.clk) then
				if this_lvt_context_in.rst = '1' then
					this_dispatch_fn_add_execute <= '0';
					this_add_out <= (busy => '0',
					return_value => (others => '0'));
					this_add_execute_in <= (run => '0',
					op => (others => '0'),
					a => (others => '0'),
					b => (others => '0'));
					this_add_out.return_value <= (others => '0');
					this_add_lvt_state <= add_lvt_idle;
				else
					case this_add_lvt_state is
						when add_lvt_idle =>
							if this_add_in.run = '1' then
								add_lvt_startup_arguments.a := this_add_in.a;
								add_lvt_startup_arguments.b := this_add_in.b;
								this_add_out.busy <= '1';
								if this_lvt_new_primitive_initialized = '1' then
									this_add_lvt_state <= add_lvt_0;
								else
									this_add_lvt_state <= add_lvt_startup;
								end if;
							end if;
						when add_lvt_startup =>
							if this_lvt_new_primitive_initialized = '1' then
								this_add_lvt_state <= add_lvt_0;
							end if;
						when add_lvt_0 =>
							this_add_execute_in.run <= '1';
							this_dispatch_fn_add_execute <= '1';
							this_add_execute_in.a <= add_lvt_startup_arguments.a;
							this_add_execute_in.b <= add_lvt_startup_arguments.b;
							this_add_execute_in.op <= signed'(x"00000001");
							this_add_lvt_state <= add_lvt_1;
						when add_lvt_1 =>
							this_add_lvt_state <= add_lvt_2;
						when add_lvt_2 =>
							this_add_execute_in.run <= '0';
							this_add_lvt_state <= add_lvt_3;
						when add_lvt_3 =>
							this_add_lvt_state <= add_lvt_4;
						when add_lvt_4 =>
							if this_add_execute_in_reference_out.busy = '0' then
								this_dispatch_fn_add_execute <= '0';
								this_add_lvt_state <= add_lvt_5;
							end if;
						when add_lvt_5 =>
							this_add_out.return_value <= this_primitive_out.result;
							this_add_lvt_state <= add_lvt_return;
						when add_lvt_return =>
							this_add_lvt_state <= add_dispatcher_pending_0;
						when add_dispatcher_pending_0 =>
							this_add_lvt_state <= add_dispatcher_pending_1;
						when add_dispatcher_pending_1 =>
							this_add_out.busy <= '0';
							this_add_lvt_state <= add_lvt_idle;
					end case;
				end if;
			end if;
		end process;
	end generate;
	add_fn_reset_async : if LVT_RESET_ASYNC generate
		add_fn : process(this_lvt_context_in.clk, this_lvt_context_in.rst) is
			variable add_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_add_in;
		begin
			if this_lvt_context_in.rst = '1' then
				this_dispatch_fn_add_execute <= '0';
				this_add_out <= (busy => '0',
				return_value => (others => '0'));
				this_add_execute_in <= (run => '0',
				op => (others => '0'),
				a => (others => '0'),
				b => (others => '0'));
				this_add_out.return_value <= (others => '0');
				this_add_lvt_state <= add_lvt_idle;
			elsif rising_edge(this_lvt_context_in.clk) then
				case this_add_lvt_state is
					when add_lvt_idle =>
						if this_add_in.run = '1' then
							add_lvt_startup_arguments.a := this_add_in.a;
							add_lvt_startup_arguments.b := this_add_in.b;
							this_add_out.busy <= '1';
							if this_lvt_new_primitive_initialized = '1' then
								this_add_lvt_state <= add_lvt_0;
							else
								this_add_lvt_state <= add_lvt_startup;
							end if;
						end if;
					when add_lvt_startup =>
						if this_lvt_new_primitive_initialized = '1' then
							this_add_lvt_state <= add_lvt_0;
						end if;
					when add_lvt_0 =>
						this_add_execute_in.run <= '1';
						this_dispatch_fn_add_execute <= '1';
						this_add_execute_in.a <= add_lvt_startup_arguments.a;
						this_add_execute_in.b <= add_lvt_startup_arguments.b;
						this_add_execute_in.op <= signed'(x"00000001");
						this_add_lvt_state <= add_lvt_1;
					when add_lvt_1 =>
						this_add_lvt_state <= add_lvt_2;
					when add_lvt_2 =>
						this_add_execute_in.run <= '0';
						this_add_lvt_state <= add_lvt_3;
					when add_lvt_3 =>
						this_add_lvt_state <= add_lvt_4;
					when add_lvt_4 =>
						if this_add_execute_in_reference_out.busy = '0' then
							this_dispatch_fn_add_execute <= '0';
							this_add_lvt_state <= add_lvt_5;
						end if;
					when add_lvt_5 =>
						this_add_out.return_value <= this_primitive_out.result;
						this_add_lvt_state <= add_lvt_return;
					when add_lvt_return =>
						this_add_lvt_state <= add_dispatcher_pending_0;
					when add_dispatcher_pending_0 =>
						this_add_lvt_state <= add_dispatcher_pending_1;
					when add_dispatcher_pending_1 =>
						this_add_out.busy <= '0';
						this_add_lvt_state <= add_lvt_idle;
				end case;
			end if;
		end process;
	end generate;
	divideeven_fn_reset_sync : if not LVT_RESET_ASYNC generate
		divideeven_fn : process(this_lvt_context_in.clk) is
			variable divideeven_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_divideeven_in;
		begin
			if rising_edge(this_lvt_context_in.clk) then
				if this_lvt_context_in.rst = '1' then
					this_dispatch_fn_divideeven_execute <= '0';
					this_divideeven_out <= (busy => '0',
					return_value => (others => '0'));
					this_divideeven_execute_in <= (run => '0',
					op => (others => '0'),
					a => (others => '0'),
					b => (others => '0'));
					this_divideeven_out.return_value <= (others => '0');
					this_divideeven_lvt_state <= divideeven_lvt_idle;
				else
					case this_divideeven_lvt_state is
						when divideeven_lvt_idle =>
							if this_divideeven_in.run = '1' then
								divideeven_lvt_startup_arguments.a := this_divideeven_in.a;
								divideeven_lvt_startup_arguments.b := this_divideeven_in.b;
								this_divideeven_out.busy <= '1';
								if this_lvt_new_primitive_initialized = '1' then
									this_divideeven_lvt_state <= divideeven_lvt_0;
								else
									this_divideeven_lvt_state <= divideeven_lvt_startup;
								end if;
							end if;
						when divideeven_lvt_startup =>
							if this_lvt_new_primitive_initialized = '1' then
								this_divideeven_lvt_state <= divideeven_lvt_0;
							end if;
						when divideeven_lvt_0 =>
							this_divideeven_execute_in.run <= '1';
							this_dispatch_fn_divideeven_execute <= '1';
							this_divideeven_execute_in.a <= divideeven_lvt_startup_arguments.a;
							this_divideeven_execute_in.b <= divideeven_lvt_startup_arguments.b;
							this_divideeven_execute_in.op <= signed'(x"00000002");
							this_divideeven_lvt_state <= divideeven_lvt_1;
						when divideeven_lvt_1 =>
							this_divideeven_lvt_state <= divideeven_lvt_2;
						when divideeven_lvt_2 =>
							this_divideeven_execute_in.run <= '0';
							this_divideeven_lvt_state <= divideeven_lvt_3;
						when divideeven_lvt_3 =>
							this_divideeven_lvt_state <= divideeven_lvt_4;
						when divideeven_lvt_4 =>
							if this_divideeven_execute_in_reference_out.busy = '0' then
								this_dispatch_fn_divideeven_execute <= '0';
								this_divideeven_lvt_state <= divideeven_lvt_5;
							end if;
						when divideeven_lvt_5 =>
							this_divideeven_out.return_value <= this_primitive_out.result;
							this_divideeven_lvt_state <= divideeven_lvt_return;
						when divideeven_lvt_return =>
							this_divideeven_lvt_state <= divideeven_dispatcher_pending_0;
						when divideeven_dispatcher_pending_0 =>
							this_divideeven_lvt_state <= divideeven_dispatcher_pending_1;
						when divideeven_dispatcher_pending_1 =>
							this_divideeven_out.busy <= '0';
							this_divideeven_lvt_state <= divideeven_lvt_idle;
					end case;
				end if;
			end if;
		end process;
	end generate;
	divideeven_fn_reset_async : if LVT_RESET_ASYNC generate
		divideeven_fn : process(this_lvt_context_in.clk, this_lvt_context_in.rst) is
			variable divideeven_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_divideeven_in;
		begin
			if this_lvt_context_in.rst = '1' then
				this_dispatch_fn_divideeven_execute <= '0';
				this_divideeven_out <= (busy => '0',
				return_value => (others => '0'));
				this_divideeven_execute_in <= (run => '0',
				op => (others => '0'),
				a => (others => '0'),
				b => (others => '0'));
				this_divideeven_out.return_value <= (others => '0');
				this_divideeven_lvt_state <= divideeven_lvt_idle;
			elsif rising_edge(this_lvt_context_in.clk) then
				case this_divideeven_lvt_state is
					when divideeven_lvt_idle =>
						if this_divideeven_in.run = '1' then
							divideeven_lvt_startup_arguments.a := this_divideeven_in.a;
							divideeven_lvt_startup_arguments.b := this_divideeven_in.b;
							this_divideeven_out.busy <= '1';
							if this_lvt_new_primitive_initialized = '1' then
								this_divideeven_lvt_state <= divideeven_lvt_0;
							else
								this_divideeven_lvt_state <= divideeven_lvt_startup;
							end if;
						end if;
					when divideeven_lvt_startup =>
						if this_lvt_new_primitive_initialized = '1' then
							this_divideeven_lvt_state <= divideeven_lvt_0;
						end if;
					when divideeven_lvt_0 =>
						this_divideeven_execute_in.run <= '1';
						this_dispatch_fn_divideeven_execute <= '1';
						this_divideeven_execute_in.a <= divideeven_lvt_startup_arguments.a;
						this_divideeven_execute_in.b <= divideeven_lvt_startup_arguments.b;
						this_divideeven_execute_in.op <= signed'(x"00000002");
						this_divideeven_lvt_state <= divideeven_lvt_1;
					when divideeven_lvt_1 =>
						this_divideeven_lvt_state <= divideeven_lvt_2;
					when divideeven_lvt_2 =>
						this_divideeven_execute_in.run <= '0';
						this_divideeven_lvt_state <= divideeven_lvt_3;
					when divideeven_lvt_3 =>
						this_divideeven_lvt_state <= divideeven_lvt_4;
					when divideeven_lvt_4 =>
						if this_divideeven_execute_in_reference_out.busy = '0' then
							this_dispatch_fn_divideeven_execute <= '0';
							this_divideeven_lvt_state <= divideeven_lvt_5;
						end if;
					when divideeven_lvt_5 =>
						this_divideeven_out.return_value <= this_primitive_out.result;
						this_divideeven_lvt_state <= divideeven_lvt_return;
					when divideeven_lvt_return =>
						this_divideeven_lvt_state <= divideeven_dispatcher_pending_0;
					when divideeven_dispatcher_pending_0 =>
						this_divideeven_lvt_state <= divideeven_dispatcher_pending_1;
					when divideeven_dispatcher_pending_1 =>
						this_divideeven_out.busy <= '0';
						this_divideeven_lvt_state <= divideeven_lvt_idle;
				end case;
			end if;
		end process;
	end generate;
	sqrt_fn_reset_sync : if not LVT_RESET_ASYNC generate
		sqrt_fn : process(this_lvt_context_in.clk) is
			variable sqrt_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_sqrt_in;
		begin
			if rising_edge(this_lvt_context_in.clk) then
				if this_lvt_context_in.rst = '1' then
					this_dispatch_fn_sqrt_execute <= '0';
					this_sqrt_out <= (busy => '0',
					return_value => (others => '0'));
					this_sqrt_execute_in <= (run => '0',
					op => (others => '0'),
					a => (others => '0'),
					b => (others => '0'));
					this_sqrt_out.return_value <= (others => '0');
					this_sqrt_lvt_state <= sqrt_lvt_idle;
				else
					case this_sqrt_lvt_state is
						when sqrt_lvt_idle =>
							if this_sqrt_in.run = '1' then
								sqrt_lvt_startup_arguments.a := this_sqrt_in.a;
								this_sqrt_out.busy <= '1';
								if this_lvt_new_primitive_initialized = '1' then
									this_sqrt_lvt_state <= sqrt_lvt_0;
								else
									this_sqrt_lvt_state <= sqrt_lvt_startup;
								end if;
							end if;
						when sqrt_lvt_startup =>
							if this_lvt_new_primitive_initialized = '1' then
								this_sqrt_lvt_state <= sqrt_lvt_0;
							end if;
						when sqrt_lvt_0 =>
							this_sqrt_execute_in.run <= '1';
							this_dispatch_fn_sqrt_execute <= '1';
							this_sqrt_execute_in.a <= sqrt_lvt_startup_arguments.a;
							this_sqrt_execute_in.b <= x"0000000000000000";
							this_sqrt_execute_in.op <= signed'(x"00000003");
							this_sqrt_lvt_state <= sqrt_lvt_1;
						when sqrt_lvt_1 =>
							this_sqrt_lvt_state <= sqrt_lvt_2;
						when sqrt_lvt_2 =>
							this_sqrt_execute_in.run <= '0';
							this_sqrt_lvt_state <= sqrt_lvt_3;
						when sqrt_lvt_3 =>
							this_sqrt_lvt_state <= sqrt_lvt_4;
						when sqrt_lvt_4 =>
							if this_sqrt_execute_in_reference_out.busy = '0' then
								this_dispatch_fn_sqrt_execute <= '0';
								this_sqrt_lvt_state <= sqrt_lvt_5;
							end if;
						when sqrt_lvt_5 =>
							this_sqrt_out.return_value <= this_primitive_out.result;
							this_sqrt_lvt_state <= sqrt_lvt_return;
						when sqrt_lvt_return =>
							this_sqrt_lvt_state <= sqrt_dispatcher_pending_0;
						when sqrt_dispatcher_pending_0 =>
							this_sqrt_lvt_state <= sqrt_dispatcher_pending_1;
						when sqrt_dispatcher_pending_1 =>
							this_sqrt_out.busy <= '0';
							this_sqrt_lvt_state <= sqrt_lvt_idle;
					end case;
				end if;
			end if;
		end process;
	end generate;
	sqrt_fn_reset_async : if LVT_RESET_ASYNC generate
		sqrt_fn : process(this_lvt_context_in.clk, this_lvt_context_in.rst) is
			variable sqrt_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_sqrt_in;
		begin
			if this_lvt_context_in.rst = '1' then
				this_dispatch_fn_sqrt_execute <= '0';
				this_sqrt_out <= (busy => '0',
				return_value => (others => '0'));
				this_sqrt_execute_in <= (run => '0',
				op => (others => '0'),
				a => (others => '0'),
				b => (others => '0'));
				this_sqrt_out.return_value <= (others => '0');
				this_sqrt_lvt_state <= sqrt_lvt_idle;
			elsif rising_edge(this_lvt_context_in.clk) then
				case this_sqrt_lvt_state is
					when sqrt_lvt_idle =>
						if this_sqrt_in.run = '1' then
							sqrt_lvt_startup_arguments.a := this_sqrt_in.a;
							this_sqrt_out.busy <= '1';
							if this_lvt_new_primitive_initialized = '1' then
								this_sqrt_lvt_state <= sqrt_lvt_0;
							else
								this_sqrt_lvt_state <= sqrt_lvt_startup;
							end if;
						end if;
					when sqrt_lvt_startup =>
						if this_lvt_new_primitive_initialized = '1' then
							this_sqrt_lvt_state <= sqrt_lvt_0;
						end if;
					when sqrt_lvt_0 =>
						this_sqrt_execute_in.run <= '1';
						this_dispatch_fn_sqrt_execute <= '1';
						this_sqrt_execute_in.a <= sqrt_lvt_startup_arguments.a;
						this_sqrt_execute_in.b <= x"0000000000000000";
						this_sqrt_execute_in.op <= signed'(x"00000003");
						this_sqrt_lvt_state <= sqrt_lvt_1;
					when sqrt_lvt_1 =>
						this_sqrt_lvt_state <= sqrt_lvt_2;
					when sqrt_lvt_2 =>
						this_sqrt_execute_in.run <= '0';
						this_sqrt_lvt_state <= sqrt_lvt_3;
					when sqrt_lvt_3 =>
						this_sqrt_lvt_state <= sqrt_lvt_4;
					when sqrt_lvt_4 =>
						if this_sqrt_execute_in_reference_out.busy = '0' then
							this_dispatch_fn_sqrt_execute <= '0';
							this_sqrt_lvt_state <= sqrt_lvt_5;
						end if;
					when sqrt_lvt_5 =>
						this_sqrt_out.return_value <= this_primitive_out.result;
						this_sqrt_lvt_state <= sqrt_lvt_return;
					when sqrt_lvt_return =>
						this_sqrt_lvt_state <= sqrt_dispatcher_pending_0;
					when sqrt_dispatcher_pending_0 =>
						this_sqrt_lvt_state <= sqrt_dispatcher_pending_1;
					when sqrt_dispatcher_pending_1 =>
						this_sqrt_out.busy <= '0';
						this_sqrt_lvt_state <= sqrt_lvt_idle;
				end case;
			end if;
		end process;
	end generate;
	clamp_fn_reset_sync : if not LVT_RESET_ASYNC generate
		clamp_fn : process(this_lvt_context_in.clk) is
			variable clamp_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_clamp_in;
		begin
			if rising_edge(this_lvt_context_in.clk) then
				if this_lvt_context_in.rst = '1' then
					this_dispatch_fn_clamp_execute <= '0';
					this_clamp_out <= (busy => '0',
					return_value => (others => '0'));
					this_clamp_execute_in <= (run => '0',
					op => (others => '0'),
					a => (others => '0'),
					b => (others => '0'));
					this_clamp_out.return_value <= (others => '0');
					this_clamp_lvt_state <= clamp_lvt_idle;
				else
					case this_clamp_lvt_state is
						when clamp_lvt_idle =>
							if this_clamp_in.run = '1' then
								clamp_lvt_startup_arguments.a := this_clamp_in.a;
								this_clamp_out.busy <= '1';
								if this_lvt_new_primitive_initialized = '1' then
									this_clamp_lvt_state <= clamp_lvt_0;
								else
									this_clamp_lvt_state <= clamp_lvt_startup;
								end if;
							end if;
						when clamp_lvt_startup =>
							if this_lvt_new_primitive_initialized = '1' then
								this_clamp_lvt_state <= clamp_lvt_0;
							end if;
						when clamp_lvt_0 =>
							this_clamp_execute_in.run <= '1';
							this_dispatch_fn_clamp_execute <= '1';
							this_clamp_execute_in.a <= clamp_lvt_startup_arguments.a;
							this_clamp_execute_in.b <= x"0000000000000000";
							this_clamp_execute_in.op <= signed'(x"00000004");
							this_clamp_lvt_state <= clamp_lvt_1;
						when clamp_lvt_1 =>
							this_clamp_lvt_state <= clamp_lvt_2;
						when clamp_lvt_2 =>
							this_clamp_execute_in.run <= '0';
							this_clamp_lvt_state <= clamp_lvt_3;
						when clamp_lvt_3 =>
							this_clamp_lvt_state <= clamp_lvt_4;
						when clamp_lvt_4 =>
							if this_clamp_execute_in_reference_out.busy = '0' then
								this_dispatch_fn_clamp_execute <= '0';
								this_clamp_lvt_state <= clamp_lvt_5;
							end if;
						when clamp_lvt_5 =>
							this_clamp_out.return_value <= signed(resize(unsigned(this_primitive_out.result), 32));
							this_clamp_lvt_state <= clamp_lvt_return;
						when clamp_lvt_return =>
							this_clamp_lvt_state <= clamp_dispatcher_pending_0;
						when clamp_dispatcher_pending_0 =>
							this_clamp_lvt_state <= clamp_dispatcher_pending_1;
						when clamp_dispatcher_pending_1 =>
							this_clamp_out.busy <= '0';
							this_clamp_lvt_state <= clamp_lvt_idle;
					end case;
				end if;
			end if;
		end process;
	end generate;
	clamp_fn_reset_async : if LVT_RESET_ASYNC generate
		clamp_fn : process(this_lvt_context_in.clk, this_lvt_context_in.rst) is
			variable clamp_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_clamp_in;
		begin
			if this_lvt_context_in.rst = '1' then
				this_dispatch_fn_clamp_execute <= '0';
				this_clamp_out <= (busy => '0',
				return_value => (others => '0'));
				this_clamp_execute_in <= (run => '0',
				op => (others => '0'),
				a => (others => '0'),
				b => (others => '0'));
				this_clamp_out.return_value <= (others => '0');
				this_clamp_lvt_state <= clamp_lvt_idle;
			elsif rising_edge(this_lvt_context_in.clk) then
				case this_clamp_lvt_state is
					when clamp_lvt_idle =>
						if this_clamp_in.run = '1' then
							clamp_lvt_startup_arguments.a := this_clamp_in.a;
							this_clamp_out.busy <= '1';
							if this_lvt_new_primitive_initialized = '1' then
								this_clamp_lvt_state <= clamp_lvt_0;
							else
								this_clamp_lvt_state <= clamp_lvt_startup;
							end if;
						end if;
					when clamp_lvt_startup =>
						if this_lvt_new_primitive_initialized = '1' then
							this_clamp_lvt_state <= clamp_lvt_0;
						end if;
					when clamp_lvt_0 =>
						this_clamp_execute_in.run <= '1';
						this_dispatch_fn_clamp_execute <= '1';
						this_clamp_execute_in.a <= clamp_lvt_startup_arguments.a;
						this_clamp_execute_in.b <= x"0000000000000000";
						this_clamp_execute_in.op <= signed'(x"00000004");
						this_clamp_lvt_state <= clamp_lvt_1;
					when clamp_lvt_1 =>
						this_clamp_lvt_state <= clamp_lvt_2;
					when clamp_lvt_2 =>
						this_clamp_execute_in.run <= '0';
						this_clamp_lvt_state <= clamp_lvt_3;
					when clamp_lvt_3 =>
						this_clamp_lvt_state <= clamp_lvt_4;
					when clamp_lvt_4 =>
						if this_clamp_execute_in_reference_out.busy = '0' then
							this_dispatch_fn_clamp_execute <= '0';
							this_clamp_lvt_state <= clamp_lvt_5;
						end if;
					when clamp_lvt_5 =>
						this_clamp_out.return_value <= signed(resize(unsigned(this_primitive_out.result), 32));
						this_clamp_lvt_state <= clamp_lvt_return;
					when clamp_lvt_return =>
						this_clamp_lvt_state <= clamp_dispatcher_pending_0;
					when clamp_dispatcher_pending_0 =>
						this_clamp_lvt_state <= clamp_dispatcher_pending_1;
					when clamp_dispatcher_pending_1 =>
						this_clamp_out.busy <= '0';
						this_clamp_lvt_state <= clamp_lvt_idle;
				end case;
			end if;
		end process;
	end generate;
	dividefloor_fn_reset_sync : if not LVT_RESET_ASYNC generate
		dividefloor_fn : process(this_lvt_context_in.clk) is
			variable dividefloor_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_dividefloor_in;
		begin
			if rising_edge(this_lvt_context_in.clk) then
				if this_lvt_context_in.rst = '1' then
					this_dispatch_fn_dividefloor_execute <= '0';
					this_dividefloor_out <= (busy => '0',
					return_value => (others => '0'));
					this_dividefloor_execute_in <= (run => '0',
					op => (others => '0'),
					a => (others => '0'),
					b => (others => '0'));
					this_dividefloor_out.return_value <= (others => '0');
					this_dividefloor_lvt_state <= dividefloor_lvt_idle;
				else
					case this_dividefloor_lvt_state is
						when dividefloor_lvt_idle =>
							if this_dividefloor_in.run = '1' then
								dividefloor_lvt_startup_arguments.a := this_dividefloor_in.a;
								dividefloor_lvt_startup_arguments.b := this_dividefloor_in.b;
								this_dividefloor_out.busy <= '1';
								if this_lvt_new_primitive_initialized = '1' then
									this_dividefloor_lvt_state <= dividefloor_lvt_0;
								else
									this_dividefloor_lvt_state <= dividefloor_lvt_startup;
								end if;
							end if;
						when dividefloor_lvt_startup =>
							if this_lvt_new_primitive_initialized = '1' then
								this_dividefloor_lvt_state <= dividefloor_lvt_0;
							end if;
						when dividefloor_lvt_0 =>
							this_dividefloor_execute_in.run <= '1';
							this_dispatch_fn_dividefloor_execute <= '1';
							this_dividefloor_execute_in.a <= dividefloor_lvt_startup_arguments.a;
							this_dividefloor_execute_in.b <= dividefloor_lvt_startup_arguments.b;
							this_dividefloor_execute_in.op <= signed'(x"00000005");
							this_dividefloor_lvt_state <= dividefloor_lvt_1;
						when dividefloor_lvt_1 =>
							this_dividefloor_lvt_state <= dividefloor_lvt_2;
						when dividefloor_lvt_2 =>
							this_dividefloor_execute_in.run <= '0';
							this_dividefloor_lvt_state <= dividefloor_lvt_3;
						when dividefloor_lvt_3 =>
							this_dividefloor_lvt_state <= dividefloor_lvt_4;
						when dividefloor_lvt_4 =>
							if this_dividefloor_execute_in_reference_out.busy = '0' then
								this_dispatch_fn_dividefloor_execute <= '0';
								this_dividefloor_lvt_state <= dividefloor_lvt_5;
							end if;
						when dividefloor_lvt_5 =>
							this_dividefloor_out.return_value <= this_primitive_out.result;
							this_dividefloor_lvt_state <= dividefloor_lvt_return;
						when dividefloor_lvt_return =>
							this_dividefloor_lvt_state <= dividefloor_dispatcher_pending_0;
						when dividefloor_dispatcher_pending_0 =>
							this_dividefloor_lvt_state <= dividefloor_dispatcher_pending_1;
						when dividefloor_dispatcher_pending_1 =>
							this_dividefloor_out.busy <= '0';
							this_dividefloor_lvt_state <= dividefloor_lvt_idle;
					end case;
				end if;
			end if;
		end process;
	end generate;
	dividefloor_fn_reset_async : if LVT_RESET_ASYNC generate
		dividefloor_fn : process(this_lvt_context_in.clk, this_lvt_context_in.rst) is
			variable dividefloor_lvt_startup_arguments : t_widearithmetic_g_24_4_sig_90219608922d_dividefloor_in;
		begin
			if this_lvt_context_in.rst = '1' then
				this_dispatch_fn_dividefloor_execute <= '0';
				this_dividefloor_out <= (busy => '0',
				return_value => (others => '0'));
				this_dividefloor_execute_in <= (run => '0',
				op => (others => '0'),
				a => (others => '0'),
				b => (others => '0'));
				this_dividefloor_out.return_value <= (others => '0');
				this_dividefloor_lvt_state <= dividefloor_lvt_idle;
			elsif rising_edge(this_lvt_context_in.clk) then
				case this_dividefloor_lvt_state is
					when dividefloor_lvt_idle =>
						if this_dividefloor_in.run = '1' then
							dividefloor_lvt_startup_arguments.a := this_dividefloor_in.a;
							dividefloor_lvt_startup_arguments.b := this_dividefloor_in.b;
							this_dividefloor_out.busy <= '1';
							if this_lvt_new_primitive_initialized = '1' then
								this_dividefloor_lvt_state <= dividefloor_lvt_0;
							else
								this_dividefloor_lvt_state <= dividefloor_lvt_startup;
							end if;
						end if;
					when dividefloor_lvt_startup =>
						if this_lvt_new_primitive_initialized = '1' then
							this_dividefloor_lvt_state <= dividefloor_lvt_0;
						end if;
					when dividefloor_lvt_0 =>
						this_dividefloor_execute_in.run <= '1';
						this_dispatch_fn_dividefloor_execute <= '1';
						this_dividefloor_execute_in.a <= dividefloor_lvt_startup_arguments.a;
						this_dividefloor_execute_in.b <= dividefloor_lvt_startup_arguments.b;
						this_dividefloor_execute_in.op <= signed'(x"00000005");
						this_dividefloor_lvt_state <= dividefloor_lvt_1;
					when dividefloor_lvt_1 =>
						this_dividefloor_lvt_state <= dividefloor_lvt_2;
					when dividefloor_lvt_2 =>
						this_dividefloor_execute_in.run <= '0';
						this_dividefloor_lvt_state <= dividefloor_lvt_3;
					when dividefloor_lvt_3 =>
						this_dividefloor_lvt_state <= dividefloor_lvt_4;
					when dividefloor_lvt_4 =>
						if this_dividefloor_execute_in_reference_out.busy = '0' then
							this_dispatch_fn_dividefloor_execute <= '0';
							this_dividefloor_lvt_state <= dividefloor_lvt_5;
						end if;
					when dividefloor_lvt_5 =>
						this_dividefloor_out.return_value <= this_primitive_out.result;
						this_dividefloor_lvt_state <= dividefloor_lvt_return;
					when dividefloor_lvt_return =>
						this_dividefloor_lvt_state <= dividefloor_dispatcher_pending_0;
					when dividefloor_dispatcher_pending_0 =>
						this_dividefloor_lvt_state <= dividefloor_dispatcher_pending_1;
					when dividefloor_dispatcher_pending_1 =>
						this_dividefloor_out.busy <= '0';
						this_dividefloor_lvt_state <= dividefloor_lvt_idle;
				end case;
			end if;
		end process;
	end generate;
	failed_fn_reset_sync : if not LVT_RESET_ASYNC generate
		failed_fn : process(this_lvt_context_in.clk) is
		begin
			if rising_edge(this_lvt_context_in.clk) then
				if this_lvt_context_in.rst = '1' then
					this_failed_out <= (busy => '0',
					return_value => false);
					this_failed_out.return_value <= false;
					this_failed_lvt_state <= failed_lvt_idle;
				else
					case this_failed_lvt_state is
						when failed_lvt_idle =>
							if this_failed_in.run = '1' then
								this_failed_out.busy <= '1';
								if this_lvt_new_primitive_initialized = '1' then
									this_failed_lvt_state <= failed_lvt_0;
								else
									this_failed_lvt_state <= failed_lvt_startup;
								end if;
							end if;
						when failed_lvt_startup =>
							if this_lvt_new_primitive_initialized = '1' then
								this_failed_lvt_state <= failed_lvt_0;
							end if;
						when failed_lvt_0 =>
							this_failed_out.return_value <= this_primitive_out.failed;
							this_failed_lvt_state <= failed_lvt_return;
						when failed_lvt_return =>
							this_failed_lvt_state <= failed_dispatcher_pending_0;
						when failed_dispatcher_pending_0 =>
							this_failed_lvt_state <= failed_dispatcher_pending_1;
						when failed_dispatcher_pending_1 =>
							this_failed_out.busy <= '0';
							this_failed_lvt_state <= failed_lvt_idle;
					end case;
				end if;
			end if;
		end process;
	end generate;
	failed_fn_reset_async : if LVT_RESET_ASYNC generate
		failed_fn : process(this_lvt_context_in.clk, this_lvt_context_in.rst) is
		begin
			if this_lvt_context_in.rst = '1' then
				this_failed_out <= (busy => '0',
				return_value => false);
				this_failed_out.return_value <= false;
				this_failed_lvt_state <= failed_lvt_idle;
			elsif rising_edge(this_lvt_context_in.clk) then
				case this_failed_lvt_state is
					when failed_lvt_idle =>
						if this_failed_in.run = '1' then
							this_failed_out.busy <= '1';
							if this_lvt_new_primitive_initialized = '1' then
								this_failed_lvt_state <= failed_lvt_0;
							else
								this_failed_lvt_state <= failed_lvt_startup;
							end if;
						end if;
					when failed_lvt_startup =>
						if this_lvt_new_primitive_initialized = '1' then
							this_failed_lvt_state <= failed_lvt_0;
						end if;
					when failed_lvt_0 =>
						this_failed_out.return_value <= this_primitive_out.failed;
						this_failed_lvt_state <= failed_lvt_return;
					when failed_lvt_return =>
						this_failed_lvt_state <= failed_dispatcher_pending_0;
					when failed_dispatcher_pending_0 =>
						this_failed_lvt_state <= failed_dispatcher_pending_1;
					when failed_dispatcher_pending_1 =>
						this_failed_out.busy <= '0';
						this_failed_lvt_state <= failed_lvt_idle;
				end case;
			end if;
		end process;
	end generate;
	primitive_instance: entity work.livt_math_arithmetic_widearithmeticprimitive
	port map (
		ctor_lvt_context_in => this_lvt_context_in,
		ctor_request => this_primitive_in.request,
		ctor_operation => this_primitive_in.operation,
		ctor_a => this_primitive_in.a,
		ctor_b => this_primitive_in.b,
		ctor_outputbits => this_primitive_in.outputbits,
		ctor_operations => this_primitive_in.operations,
		ctor_acknowledge => this_primitive_acknowledge,
		ctor_result => this_primitive_result,
		ctor_failed => this_primitive_failed
	);
	
end;
