-- Copyright (C) 2026 Eccelerators GmbH
--
-- This code was generated by:
--
-- Livt Compiler v0.0.0-0000000
-- VHDL Extension for Livt v0.0.0-0000000
--
-- Further information at https://eccelerators.com/livt
--
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

library work;
  use work.livt_lang_icontext_package.all;

package livt_lang_icomponent_package is

	type t_icomponent_in is
	record
		lvt_context : t_icontext_in;
	end record;
	
end;

package body livt_lang_icomponent_package is

end;
