-- Copyright (C) 2026 Eccelerators GmbH
--
-- This code was generated by:
--
-- Livt Compiler v0.0.0-0000000
-- VHDL Extension for Livt v0.0.0-0000000
--
-- Further information at https://eccelerators.com/livt
--
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

use work.livt_lang_icomponent_package.all;
use work.livt_lang_icontext_package.all;
use work.livt_lang_package.all;
use work.livt_math_arithmetic_widearithmetic_g_24_4_sig_90219608922d_package.all;
use work.livt_math_arithmetic_widearithmeticprimitive_package.all;

entity bench is port (
		clk, rst : in std_logic;
		multiply_in : in t_widearithmetic_g_24_4_sig_90219608922d_multiply_in;
		multiply_out : out t_widearithmetic_g_24_4_sig_90219608922d_multiply_out;
		add_in : in t_widearithmetic_g_24_4_sig_90219608922d_add_in;
		add_out : out t_widearithmetic_g_24_4_sig_90219608922d_add_out;
		divideeven_in : in t_widearithmetic_g_24_4_sig_90219608922d_divideeven_in;
		divideeven_out : out t_widearithmetic_g_24_4_sig_90219608922d_divideeven_out;
		sqrt_in : in t_widearithmetic_g_24_4_sig_90219608922d_sqrt_in;
		sqrt_out : out t_widearithmetic_g_24_4_sig_90219608922d_sqrt_out;
		clamp_in : in t_widearithmetic_g_24_4_sig_90219608922d_clamp_in;
		clamp_out : out t_widearithmetic_g_24_4_sig_90219608922d_clamp_out;
		dividefloor_in : in t_widearithmetic_g_24_4_sig_90219608922d_dividefloor_in;
		dividefloor_out : out t_widearithmetic_g_24_4_sig_90219608922d_dividefloor_out;
		failed_in : in t_widearithmetic_g_24_4_sig_90219608922d_failed_in;
		failed_out : out t_widearithmetic_g_24_4_sig_90219608922d_failed_out);end;
architecture rtl of bench is
signal ctx:t_icontext_in;
begin
ctx <= (clk,rst,to_unsigned(50000000,32),to_unsigned(20,32),to_unsigned(10,32),to_unsigned(10,32));
dut:entity work.livt_math_arithmetic_widearithmetic_g_24_4_sig_90219608922d port map(ctor_lvt_context_in=>ctx,multiply_in=>multiply_in,multiply_out=>multiply_out,add_in=>add_in,add_out=>add_out,divideeven_in=>divideeven_in,divideeven_out=>divideeven_out,sqrt_in=>sqrt_in,sqrt_out=>sqrt_out,clamp_in=>clamp_in,clamp_out=>clamp_out,dividefloor_in=>dividefloor_in,dividefloor_out=>dividefloor_out,failed_in=>failed_in,failed_out=>failed_out);
end;
