-- Copyright (C) 2026 Eccelerators GmbH
--
-- This code was generated by:
--
-- Livt Compiler v0.0.0-0000000
-- VHDL Extension for Livt v0.0.0-0000000
--
-- Further information at https://eccelerators.com/livt
--
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

use work.livt_lang_package.all;

package livt_math_arithmetic_widearithmeticprimitive_package is

	-- Component types
	type t_widearithmeticprimitive_in is
	record
		request : std_logic;
		operation : signed(31 downto 0);
		a : std_logic_vector(63 downto 0);
		b : std_logic_vector(63 downto 0);
		outputbits : signed(31 downto 0);
		operations : signed(31 downto 0);
	end record;
	
	type t_widearithmeticprimitive_out is
	record
		acknowledge : std_logic;
		result : std_logic_vector(63 downto 0);
		failed : boolean;
	end record;
	
end;

package body livt_math_arithmetic_widearithmeticprimitive_package is

end;
