-- Copyright (C) 2026 Eccelerators GmbH
--
-- This code was generated by:
--
-- Livt Compiler v0.0.0-0000000
-- VHDL Extension for Livt v0.0.0-0000000
--
-- Further information at https://eccelerators.com/livt
--
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

package livt_lang_package is

	subtype byte is std_logic_vector(7 downto 0);
	subtype livt_uint is unsigned(31 downto 0);

	constant REF_WAIT_CYCLES : integer := 3;
	constant CTOR_WAIT_CYCLE : integer := 3;
	constant LIVT_LANG_MAX_STRING_LENGTH : natural := 1024;

	-- Enum ResetStyle
	type livt_enum_4c6976742e4c616e672e416e6e6f746174696f6e732e52657365745374796c65 is (
		livt_enum_4c6976742e4c616e672e416e6e6f746174696f6e732e52657365745374796c65_value_53796e6368726f6e6f7573,
		livt_enum_4c6976742e4c616e672e416e6e6f746174696f6e732e52657365745374796c65_value_4173796e6368726f6e6f7573
	);
	-- Array types
	type integer_array_1d is array (
		natural range <>
	) of signed(31 downto 0);
	
	type logic_array_2d is array (
		natural range <>, 
		natural range <>
	) of std_logic;
	
	type string_array_1d is array (
		natural range <>
	) of string;
	
	-- Array functions
	function get_logic_array_2d_arity_1(matrix: logic_array_2d; d1: integer) return std_logic_vector;
	
	procedure set_logic_array_2d_arity_1(matrix: inout logic_array_2d; d1: integer; value: std_logic_vector);
	procedure set_signal_logic_array_2d_arity_1(signal matrix: inout logic_array_2d; d1: integer; value: std_logic_vector);
	
	function resize(src: integer_array_1d; new_size: natural) return integer_array_1d;
	
	function resize(src: logic_array_2d; new_size_1: natural; new_size_2: natural) return logic_array_2d;
	
	function to_string(value: std_logic_vector) return string;

-- vivado-preprocess: 	function to_string(value: integer_vector) return string;

-- vivado-preprocess: 	function to_string(value: boolean_vector) return string;

	function character_encode(c : character) return std_logic_vector;

	function string_encode(s : string) return logic_array_2d;

	function string_decode(b : logic_array_2d) return string;

	function livt_ticks_for(duration_ns : natural; period_ns : livt_uint) return livt_uint;

	function livt_ticks_per(ticks_per_second : livt_uint; frequency_hz : positive) return livt_uint;
	function livt_static_frequency(value : real) return positive;
	function livt_static_duration(value : real) return natural;

end;

package body livt_lang_package is

-- Array functions
function get_logic_array_2d_arity_1(matrix: logic_array_2d; d1: integer)
	return std_logic_vector
is
	variable slice : std_logic_vector(matrix'high(2) downto matrix'low(2));
begin
	for d2 in slice'range loop
		slice(d2) := matrix(d1, d2);
	end loop;
	return slice;
end;

procedure set_logic_array_2d_arity_1(matrix: inout logic_array_2d; d1: integer; value: std_logic_vector) is
	variable normalized : std_logic_vector(matrix'high(2) downto matrix'low(2));
begin
	normalized := value;
	for d2 in matrix'range(2) loop
		matrix(d1, d2) := normalized(d2);
	end loop;
end;

procedure set_signal_logic_array_2d_arity_1(signal matrix: inout logic_array_2d; d1: integer; value: std_logic_vector) is
	variable normalized : std_logic_vector(matrix'high(2) downto matrix'low(2));
begin
	normalized := value;
	for d2 in matrix'range(2) loop
		matrix(d1, d2) <= normalized(d2);
	end loop;
end;

function resize(src: integer_array_1d; new_size: natural) return integer_array_1d is
	variable result : integer_array_1d(new_size - 1 downto 0) := (others => (others => '0'));
begin
	for i in src'range loop
		if i - src'low < result'length then
			result(i - src'low + result'low) := src(i);
		end if;
	end loop;
	return result;
end function;

function resize(src: logic_array_2d; new_size_1: natural; new_size_2: natural) return logic_array_2d is
	variable result : logic_array_2d(new_size_1 - 1 downto 0, new_size_2 - 1 downto 0) := (others => (others => '0'));
begin
	for i1 in src'range(1) loop
		for i2 in src'range(2) loop
			if i1 - src'low(1) < result'length(1) and i2 - src'low(2) < result'length(2) then
				result(i1 - src'low(1) + result'low(1), i2 - src'low(2) + result'low(2)) := src(i1, i2);
			end if;
		end loop;
	end loop;
	return result;
end function;

function to_string(value: std_logic_vector) return string is
	variable result: string(1 to value'length);
	variable result_index: integer := 1;
begin
	for i in value'range loop
		result(result_index) := std_logic'image(value(i))(2);
		result_index := result_index + 1;
	end loop;
	return result;
end function;

-- vivado-preprocess: 	function to_string(value: integer_vector) return string is
-- vivado-preprocess: 		variable result: string(1 to value'length);
-- vivado-preprocess: 		variable result_index: integer := 1;
-- vivado-preprocess: 	begin
-- vivado-preprocess: 		for i in value'range loop
-- vivado-preprocess: 			result(result_index) := integer'image(value(i))(2);
-- vivado-preprocess: 			result_index := result_index + 1;
-- vivado-preprocess: 		end loop;
-- vivado-preprocess: 		return result;
-- vivado-preprocess: 	end function;

-- vivado-preprocess: 	function to_string(value: boolean_vector) return string is
-- vivado-preprocess: 		variable result: string(1 to value'length);
-- vivado-preprocess: 		variable result_index: integer := 1;
-- vivado-preprocess: 	begin
-- vivado-preprocess: 		for i in value'range loop
-- vivado-preprocess: 			result(result_index) := boolean'image(value(i))(2);
-- vivado-preprocess: 			result_index := result_index + 1;
-- vivado-preprocess: 		end loop;
-- vivado-preprocess: 		return result;
-- vivado-preprocess: 	end function;
	
	function character_encode(c : character) return std_logic_vector is
	begin
	return std_logic_vector(to_unsigned(character'pos(c), 8));
	end function;
	
	function string_encode(s : string) return logic_array_2d is
		variable result : logic_array_2d(s'high downto s'low, 7 downto 0);
		variable tmp : std_logic_vector(7 downto 0);
	begin
		for i in s'high downto s'low loop
			tmp := character_encode(s(i));
			for b in tmp'range loop
				result(i, b) := tmp(b);
			end loop;
		end loop;
		return result;
	end function;
	
	function string_decode(b : logic_array_2d) return string is
		variable result : string(1 to b'LENGTH(1));
	begin
		for i in 0 to b'LENGTH(1) - 1 loop
			result(i + 1) := character'val(to_integer(unsigned(get_logic_array_2d_arity_1(b, b'low(1) + i))));
		end loop;
		return result;
	end function;

	function livt_ticks_for(duration_ns : natural; period_ns : livt_uint) return livt_uint is
		variable period : natural := 0;
	begin
		if is_x(std_logic_vector(period_ns)) then
			return to_unsigned(0, 32);
		end if;
		period := to_integer(period_ns);
		if period = 0 then
			return to_unsigned(0, 32);
		end if;
		if duration_ns mod period = 0 then
			return to_unsigned(duration_ns / period, 32);
		end if;
		return to_unsigned(duration_ns / period + 1, 32);
	end function;

	function livt_static_frequency(value : real) return positive is
	begin
		assert value > 0.0 and value <= 2147483647.0
			report "TicksPer frequency must be positive and at most 2147483647Hz" severity failure;
		assert real(integer(value)) = value
			report "TicksPer frequency must be a whole number of hertz" severity failure;
		return positive(value);
	end function;

	function livt_static_duration(value : real) return natural is
	begin
		assert value >= 0.0 and value < 2147483647.5
			report "TicksFor duration must round to 0..2147483647 nanoseconds" severity failure;
		return natural(value);
	end function;

	function livt_ticks_per(ticks_per_second : livt_uint; frequency_hz : positive) return livt_uint is
		variable quotient : livt_uint := (others => '0');
		variable remainder : livt_uint := (others => '0');
		variable half_frequency : livt_uint := to_unsigned(frequency_hz / 2 + frequency_hz mod 2, 32);
	begin
		if is_x(std_logic_vector(ticks_per_second)) or ticks_per_second = 0 then
			return to_unsigned(0, 32);
		end if;
		quotient := ticks_per_second / frequency_hz;
		remainder := ticks_per_second mod frequency_hz;
		if remainder >= half_frequency then
			quotient := quotient + 1;
		end if;
		if quotient = 0 then
			return to_unsigned(1, 32);
		end if;
		return quotient;
	end function;
	
end;

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity livt_cdc_toggle_synchronizer is
port (
	clk : in std_logic;
	rst : in std_logic;
	toggle_in : in std_logic;
	toggle_out : out std_logic;
	toggle_edge : out std_logic
);
end entity;

architecture rtl of livt_cdc_toggle_synchronizer is
	signal sync_1 : std_logic := '0';
	signal sync_2 : std_logic := '0';
	signal seen : std_logic := '0';
begin
	process(clk)
	begin
		if rising_edge(clk) then
			if rst = '1' then
				sync_1 <= '0';
				sync_2 <= '0';
				seen <= '0';
			else
				sync_1 <= toggle_in;
				sync_2 <= sync_1;
				seen <= sync_2;
			end if;
		end if;
	end process;
	
	toggle_out <= sync_2;
	toggle_edge <= sync_2 xor seen;
end architecture;

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

entity livt_cdc_transaction is
generic (
	request_width : positive := 1;
	response_width : positive := 1
);
port (
	source_clk : in std_logic;
	source_rst : in std_logic;
	source_start : in std_logic;
	source_payload : in std_logic_vector(request_width - 1 downto 0);
	source_busy : out std_logic;
	source_done : out std_logic;
	source_response : out std_logic_vector(response_width - 1 downto 0);
	target_clk : in std_logic;
	target_rst : in std_logic;
	target_request : out std_logic;
	target_payload : out std_logic_vector(request_width - 1 downto 0);
	target_response : in std_logic_vector(response_width - 1 downto 0);
	target_response_valid : in std_logic
);
end entity;

architecture rtl of livt_cdc_transaction is
	signal source_payload_hold : std_logic_vector(request_width - 1 downto 0) := (others => '0');
	signal source_response_hold : std_logic_vector(response_width - 1 downto 0) := (others => '0');
	signal source_busy_hold : std_logic := '0';
	signal source_done_hold : std_logic := '0';
	signal request_toggle_source : std_logic := '0';
	signal acknowledge_toggle_target : std_logic := '0';
	signal acknowledge_seen_source : std_logic := '0';
	signal acknowledge_synced_source : std_logic := '0';
	signal acknowledge_edge_source : std_logic := '0';
	signal request_seen_target : std_logic := '0';
	signal request_synced_target : std_logic := '0';
	signal request_edge_target : std_logic := '0';
	signal target_busy_hold : std_logic := '0';
	signal target_request_hold : std_logic := '0';
	signal target_payload_hold : std_logic_vector(request_width - 1 downto 0) := (others => '0');
	signal target_response_hold : std_logic_vector(response_width - 1 downto 0) := (others => '0');
begin
	request_synchronizer : entity work.livt_cdc_toggle_synchronizer
	port map (
		clk => target_clk,
		rst => target_rst,
		toggle_in => request_toggle_source,
		toggle_out => request_synced_target,
		toggle_edge => request_edge_target
	);
	
	acknowledge_synchronizer : entity work.livt_cdc_toggle_synchronizer
	port map (
		clk => source_clk,
		rst => source_rst,
		toggle_in => acknowledge_toggle_target,
		toggle_out => acknowledge_synced_source,
		toggle_edge => acknowledge_edge_source
	);
	
	process(source_clk)
	begin
		if rising_edge(source_clk) then
			if source_rst = '1' then
				source_payload_hold <= (others => '0');
				source_response_hold <= (others => '0');
				source_busy_hold <= '0';
				source_done_hold <= '0';
				request_toggle_source <= '0';
				acknowledge_seen_source <= '0';
			else
				source_done_hold <= '0';
				if source_busy_hold = '0' then
					if source_start = '1' then
						source_payload_hold <= source_payload;
						request_toggle_source <= not request_toggle_source;
						source_busy_hold <= '1';
					end if;
				elsif acknowledge_synced_source /= acknowledge_seen_source then
					acknowledge_seen_source <= acknowledge_synced_source;
					source_response_hold <= target_response_hold;
					source_busy_hold <= '0';
					source_done_hold <= '1';
				end if;
			end if;
		end if;
	end process;
	
	process(target_clk)
	begin
		if rising_edge(target_clk) then
			if target_rst = '1' then
				request_seen_target <= '0';
				target_busy_hold <= '0';
				target_request_hold <= '0';
				target_payload_hold <= (others => '0');
				target_response_hold <= (others => '0');
				acknowledge_toggle_target <= '0';
			else
				target_request_hold <= '0';
				if target_busy_hold = '0' then
					if request_synced_target /= request_seen_target then
						request_seen_target <= request_synced_target;
						target_payload_hold <= source_payload_hold;
						target_request_hold <= '1';
						target_busy_hold <= '1';
					end if;
				elsif target_response_valid = '1' then
					target_response_hold <= target_response;
					acknowledge_toggle_target <= not acknowledge_toggle_target;
					target_busy_hold <= '0';
				end if;
			end if;
		end if;
	end process;
	
	source_busy <= source_busy_hold;
	source_done <= source_done_hold;
	source_response <= source_response_hold;
	target_request <= target_request_hold;
	target_payload <= target_payload_hold;
end architecture;
