[project]
name = "Livt.Math"
version = "0.3.0"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
    "SqrtLUTTest",
    "SqrtNewtonRaphsonTest",
    "MacUnitTest",
    "Q7Test",
    "Q15Test",
    "UQ8Test",
    "ComplexQ15Test",
    "TrigQ15Test",
    "Lcg16Test",
    "Xorshift24Test"
]

[dependencies]
Livt.Base = "0.1.1"

[build.debug]
warnings = ["all", "no-variable-divisor"]

[build.release]
warnings = ["all"]
