[project]
name = "Livt.Math"
version = "0.1.0"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
    "SqrtLUTTest",
    "SqrtNewtonRaphsonTest",
    "MacUnitTest",
    "Lcg16Test",
    "Xorshift24Test"
]

[dependencies]
Livt.Base = "0.1.0"
