[project]
name = "Livt.Math"
version = "1.0.0"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
    "SqrtLUTTest",
    "SqrtNewtonRaphsonTest",
    "MacUnitTest",
    "MacInt32Test",
    "Q7Test",
    "Q15Test",
    "UQ8Test",
    "ComplexQ15Test",
    "TrigQ15Test",
    "Lcg16Test",
    "Xorshift24Test",
    "SqrtInt32Test",
    "ReciprocalSqrtQ15Test",
    "TanhQ15Test"
]

[dependencies]
Livt.Base = "1.0.0"

[build.debug]
warnings = ["all"]

[build.release]
warnings = ["all"]
