-- Copyright (C) 2026 Eccelerators GmbH
--
-- This code was generated by:
--
-- Livt Compiler v0.0.0-0000000
-- VHDL Extension for Livt v0.0.0-0000000
--
-- Further information at https://eccelerators.com/livt
--
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

use work.livt_lang_icontext_package.all;
use work.livt_lang_package.all;
use work.livt_math_arithmetic_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_package.all;
use work.livt_math_arithmetic_unsigneddivision_g_31_sig_00e979e2352c_package.all;

entity livt_math_arithmetic_unsigneddivision_g_31_sig_00e979e2352c_slice is
port (Clk: in std_logic; Rst: in std_logic;
compute_in : in t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_compute_in;
compute_out : out t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_compute_out;
getquotient_in : in t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_getquotient_in;
getquotient_out : out t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_getquotient_out;
getremainder_in : in t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_getremainder_in;
getremainder_out : out t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_getremainder_out;
divide_in : in t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_divide_in;
divide_out : out t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_divide_out;
remainder_in : in t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_remainder_in;
remainder_out : out t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_remainder_out;
moduloeuclidean_in : in t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_moduloeuclidean_in;
moduloeuclidean_out : out t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_moduloeuclidean_out;
failed_in : in t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_failed_in;
failed_out : out t_iintegerdivision_g_unsignedinteger_sig_809b61f6ff02_failed_out);
end;
architecture rtl of livt_math_arithmetic_unsigneddivision_g_31_sig_00e979e2352c_slice is begin
dut: entity work.livt_math_arithmetic_unsigneddivision_g_31_sig_00e979e2352c port map (ctor_lvt_context_in => (clk => Clk, rst => Rst, tickspersecond => to_unsigned(50000000,32), periodns => to_unsigned(20,32), hightimens => to_unsigned(10,32), lowtimens => to_unsigned(10,32)),
compute_in => compute_in,
compute_out => compute_out,
getquotient_in => getquotient_in,
getquotient_out => getquotient_out,
getremainder_in => getremainder_in,
getremainder_out => getremainder_out,
divide_in => divide_in,
divide_out => divide_out,
remainder_in => remainder_in,
remainder_out => remainder_out,
moduloeuclidean_in => moduloeuclidean_in,
moduloeuclidean_out => moduloeuclidean_out,
failed_in => failed_in,
failed_out => failed_out);
end;
