-- Copyright (C) 2026 Eccelerators GmbH
--
-- This code was generated by:
--
-- Livt Compiler v0.0.0-0000000
-- VHDL Extension for Livt v0.0.0-0000000
--
-- Further information at https://eccelerators.com/livt
--
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

use work.livt_lang_package.all;
use work.livt_math_arithmetic_widearithmeticprimitive_package.all;

package livt_math_arithmetic_widearithmetic_g_24_31_sig_93dd70859d1b_package is

	-- Function types
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_execute_in is
	record
		op : signed(31 downto 0);
		a : std_logic_vector(63 downto 0);
		b : std_logic_vector(63 downto 0);
		run : std_logic;
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_execute_out is
	record
		busy : std_logic;
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_multiply_in is
	record
		a : std_logic_vector(63 downto 0);
		b : std_logic_vector(63 downto 0);
		run : std_logic;
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_multiply_out is
	record
		busy : std_logic;
		return_value : std_logic_vector(63 downto 0);
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_add_in is
	record
		a : std_logic_vector(63 downto 0);
		b : std_logic_vector(63 downto 0);
		run : std_logic;
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_add_out is
	record
		busy : std_logic;
		return_value : std_logic_vector(63 downto 0);
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_divideeven_in is
	record
		a : std_logic_vector(63 downto 0);
		b : std_logic_vector(63 downto 0);
		run : std_logic;
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_divideeven_out is
	record
		busy : std_logic;
		return_value : std_logic_vector(63 downto 0);
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_sqrt_in is
	record
		a : std_logic_vector(63 downto 0);
		run : std_logic;
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_sqrt_out is
	record
		busy : std_logic;
		return_value : std_logic_vector(63 downto 0);
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_clamp_in is
	record
		a : std_logic_vector(63 downto 0);
		run : std_logic;
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_clamp_out is
	record
		busy : std_logic;
		return_value : signed(31 downto 0);
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_dividefloor_in is
	record
		a : std_logic_vector(63 downto 0);
		b : std_logic_vector(63 downto 0);
		run : std_logic;
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_dividefloor_out is
	record
		busy : std_logic;
		return_value : std_logic_vector(63 downto 0);
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_failed_in is
	record
		run : std_logic;
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_failed_out is
	record
		busy : std_logic;
		return_value : boolean;
	end record;
	
	-- Component types
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_in is
	record
		multiply : t_widearithmetic_g_24_31_sig_93dd70859d1b_multiply_in;
		add : t_widearithmetic_g_24_31_sig_93dd70859d1b_add_in;
		divideeven : t_widearithmetic_g_24_31_sig_93dd70859d1b_divideeven_in;
		sqrt : t_widearithmetic_g_24_31_sig_93dd70859d1b_sqrt_in;
		clamp : t_widearithmetic_g_24_31_sig_93dd70859d1b_clamp_in;
		dividefloor : t_widearithmetic_g_24_31_sig_93dd70859d1b_dividefloor_in;
		failed : t_widearithmetic_g_24_31_sig_93dd70859d1b_failed_in;
	end record;
	
	type t_widearithmetic_g_24_31_sig_93dd70859d1b_out is
	record
		multiply : t_widearithmetic_g_24_31_sig_93dd70859d1b_multiply_out;
		add : t_widearithmetic_g_24_31_sig_93dd70859d1b_add_out;
		divideeven : t_widearithmetic_g_24_31_sig_93dd70859d1b_divideeven_out;
		sqrt : t_widearithmetic_g_24_31_sig_93dd70859d1b_sqrt_out;
		clamp : t_widearithmetic_g_24_31_sig_93dd70859d1b_clamp_out;
		dividefloor : t_widearithmetic_g_24_31_sig_93dd70859d1b_dividefloor_out;
		failed : t_widearithmetic_g_24_31_sig_93dd70859d1b_failed_out;
	end record;
	
end;

package body livt_math_arithmetic_widearithmetic_g_24_31_sig_93dd70859d1b_package is

end;
